### ISSUE TITLE
“添加文章”按钮太难找

### ISSUE THREAD

**Issue by LyZane** [b3log/symphony#103]
在几乎所有页面都有个“个人简介”，自己看自己的个人简介是什么敢脚？
是自拍的敢脚……

把“添加文章”的按钮放在自拍框里又小又难找。

最初我找发布文章的按钮，以为进了文章列表（/member/user）应该会有，然并卵，不科学啊老湿。

最后：建议放在最顶端的导航条上。

**Comment by 88250** [comment]
是有点扯现在这个设计，放上去弄成个 + 号图标似乎还是很好看的

@Vanessa219

**Comment by Vanessa219** [comment]
文章页面可以取到作者 person-info.ftl 里面相关的内容么？
可以的话，可以把那块换成文章作者的
