### ISSUE TITLE
使用百度搜索

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#108]

**Comment by jingxuetao** [comment]
what do you want to do?github我不怎么会用。。

**Comment by jingxuetao** [comment]
Please change the B3log default search to baidu search

**Comment by 88250** [comment]
@jingxuetao 嗯，已经确定要换成百度搜索了，估计下午上线。

**Comment by jingxuetao** [comment]
是0.7.0吗？

**Comment by 88250** [comment]
@jingxuetao 什么 0.7.0？

**Comment by jingxuetao** [comment]
我说的是B3log...

**Comment by jingxuetao** [comment]
不是说社区。。

**Comment by 88250** [comment]
晕。。。。Solo 的搜索啊，也一并改了吧，下个版本是 1.0.0

**Comment by jingxuetao** [comment]
那b3log怎么改？

**Comment by 88250** [comment]
@jingxuetao 改皮肤就行，下个版本发布后有搜索的皮肤都会改成使用百度搜索
