### ISSUE TITLE
【BUG】基本信息设置

### ISSUE THREAD

**Issue by LyZane** [b3log/symphony#116]
不管是否填写“自我标签”项，在保存的时候都提示：
```
最多包含 7 个标签，每个标签长度 1-50，请勿包含特殊符号
```

**Comment by LyZane** [comment]
又测试了一下，发现是不能为空，也不能带中文符号。写纯中文就可以了。

**Comment by 88250** [comment]
嗯，不能用符号

**Comment by LyZane** [comment]
这个提示信息很不友好，不能为空要说清楚嘛……=。=
而且为空的时候提示信息弹出位置是在“自我标签”输入框处，离保存按钮很远，根本看不到，狂点保存没反映完全不知道发生了什么。
输入“奔放的胸毛。”之后保存，提示信息内容一样，但出现的未知在保存按钮左侧，这种体验好分裂！

至少有半个人都不好了

**Comment by 88250** [comment]
嗯，明白，会继续完善的。
