### ISSUE TITLE
HTTPS 下 ws:// 协议报错

### ISSUE THREAD

**Issue by pupboss** [b3log/symphony#133]
把 macro-list.ftl, article.ftl, timeline.ftl 中相关的改成 wss:// 还是报错

**Comment by 88250** [comment]
其他部分正常么？

**Comment by pupboss** [comment]
你好，谢谢回复，稍后我写一个详细的问题说明

别的问题其实也不少东西文档没提，比如七牛的图片裁剪，邮件的模板，目前都解决的还可以

**Comment by pupboss** [comment]
修改成 wss:// 是这样的：有 error 和 log 和 warning
![IMG01](https://ooo.0o0.ooo/2015/10/05/56122084ed32c.png "QQ20151005-0.png")
![IMG02](https://ooo.0o0.ooo/2015/10/05/561220b855ab0.png "QQ20151005-1.png")

修改前是这样的：有 log 和 warning

![IMG03](https://ooo.0o0.ooo/2015/10/05/56122130a6d72.png "QQ20151005-2.png")
![IMG04](https://ooo.0o0.ooo/2015/10/05/56122174cace6.png "QQ20151005-3.png")

**Comment by 88250** [comment]
服务端有报错么？

**Comment by pupboss** [comment]
用 bin/jetty.sh 方式启动的时候，在 logs/2015_10_05.stderrout.log 里面只有一些常规的日志，没有4xx，5xx 错误，用 jar 方式启动的时候，启动之后出现了几个 warn

```
# java -jar start.jar 

2015-10-05 15:10:00.793:INFO:oejs.Server:main: Started @4429ms
[WARN ]-[2015-10-05 15:10:52]-[org.b3log.latke.servlet.handler.AdviceHandler:235]: Occured an exception before request processing [errMsg=403, /pre-post]
[WARN ]-[2015-10-05 15:11:54]-[org.b3log.latke.servlet.handler.AdviceHandler:235]: Occured an exception before request processing [errMsg=403, /post]
[WARN ]-[2015-10-05 15:12:00]-[org.b3log.latke.servlet.handler.AdviceHandler:235]: Occured an exception before request processing [errMsg=403, /update]
```

**Comment by 88250** [comment]
HTTPS 访问页面正常么？ （你应该已经修改了 latke.props 了吧？）

**Comment by pupboss** [comment]
对的，访问正常，配置方法是 host=域名，port 不设置，用的 Nginx 反代。网站地址是 https://lntu.org  :)

**Comment by pupboss** [comment]
Terms 说 `You can not get rid of the "Powered by B3log 开源" from any page, even which you made`，所以别的地方多多少少都有改动，您看哪个地方侵犯了著作权，我改回去

**Comment by 88250** [comment]
![image](https://cloud.githubusercontent.com/assets/873584/10275088/35560230-6b77-11e5-9b43-f49731d083ea.png)

这样 :-)

你拉一下最新代码看看。

**Comment by pupboss** [comment]
我是昨天才开始用的，最新的更新是一个字体的大小，已经调整，好象是没什么用，问题还是存在。

不过这个社区暂时不打算开放~先就这样吧，等您下次更新

![IMG01](https://ooo.0o0.ooo/2015/10/05/56122b63eb3ca.png "QQ20151005-0.png")

**Comment by 88250** [comment]
嗯，WSS 这个估计短期内我没有空看了，还是非常希望你来跟进 :grapes:

**Comment by pupboss** [comment]
哈哈，其实我也想跟进，我是个写 OC，Python 的。java 也就是能看懂大致结构 :laughing: 

iOS 版那个客户端有可能会参与进来

**Comment by 88250** [comment]
嗯，先这样吧。无论如何，多谢了 :sun_with_face:
