### ISSUE TITLE
支持 Tomcat 不限定 Servlet 容器

### ISSUE THREAD

**Issue by shenzhuan** [b3log/symphony#154]
我看到你这个blog 速度快 功能强大，但是只支持jetty，有点不好，希望有个tomcat版本的

**Comment by shenzhuan** [comment]
我看到你这个blog 速度快 功能强大，但是只支持jetty，有点不好，希望有个tomcat版本的

**Comment by 88250** [comment]
这个不是博客，是个社区系统....
