### ISSUE TITLE
支持上传非图片文件

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#185]
积分用处比较多的一般都是积分下载（比如CSDN的下载频道，以前的百度文库下载，传统的论坛附件购买等）和积分兑换（兑红包、礼品或者会员服务等），综合考虑目前sym的功能，打赏区可增加积分下载一项。功能建议：
1、文件上传类型和大小限制：主要是压缩包附件，通过配置文件参数设置大小。
2、压缩包上传后在帖子下方自动生成下载按钮。
3、思考1：下载后是否对分享内容进行评论奖励，资源评级可给后面需要的人作为参考，不过目前跟论坛的积分规则有冲突:。
4、思考2：文本打赏是否跟积分下载分开但界面和操作又不复杂。
5、思考3：下载是否加密。

**Comment by 88250** [comment]
将在编辑器（不只是打赏区）统一提供文件上传按钮。

1. 不限制文件类型了，只限制文件大小，通过 symphony.props 配置
2. 会将下载链接嵌入到内容中（类似处理图片上传那要）

* 思考1：暂时不做这样的特性，等以后再讨论看看吧
* 思考2：不分开了，统一用打赏区
* 思考3：你指的加密是？

**Comment by luhua** [comment]
加密就是不显示真实URL和判断来源地址

**Comment by 88250** [comment]
@luhua 下载链接不加密了，不过可以判断一下来源，如果不是本站请求，就拒绝掉。

**Comment by luhua** [comment]
ok

**Comment by luhua** [comment]
这是不是也是上传到七牛的？如果是上传本地的话，是需要限制类型的，防止上传脚本木马~

**Comment by 88250** [comment]
@luhua 嗯，上传七牛。（本地也可以上传，暂时不判断类型了）

**Comment by 88250** [comment]
@luhua 来源判断暂时不弄了，用七牛的话可以用他们的防盗链功能。
