### ISSUE TITLE
附加功能个人配置

### ISSUE THREAD

**Issue by 40780083** [b3log/symphony#189]
附加功能添置配置项。
  要考虑到用户自己的工作，浏览网站的习惯。 
  比如 chrome 通知，自动显示用户登录环境等等，添加配置项可以增加用户体验。

建议添加：

1. 用户配置功能
    * 是否启用 Chrome 通知
2. 用户隐私配置功能
    * 是否显示 UA 信息
    * 是否显示城市信息

**Comment by 88250** [comment]
收到，会考虑加入的，多谢反馈 :grapes:
