### ISSUE TITLE
建议，能否把没用的功能去掉？

### ISSUE THREAD

**Issue by bfxyly** [b3log/symphony#191]
首先很赞赏这个开源论坛，提几个建议。
那个标签功能，能否去掉？谁会没事的点标签？请把标签替代成分类。
作为一个用户，真心不关心那些乱七八糟的标签，我只关心帖子内容。
作为一个站长，同样不关心标签什么的，那是个没用的东西。
咱就想要一个实用的，不要花里胡哨的，必须有的功能必须有，没必要的功能直接去掉。
那个此刻xxx用户正在干什么的，这也完全是没用的功能，做出来的功能对用户一点用处都没有，嘛，炫耀除外。
论坛不需要加搜索功能，这个也没必要。

用了一大堆技术，真正用户需要的东西，就是帖子（主要），回复，时间显示，帖子之间的回复，残废的分类功能，就这么几个。

就写这么多吧，反正很好看，但是没法用。

**Comment by luhua** [comment]
标签就是用来替代分类的，文章可以一对多，比传统的分类灵活多了。这个是SYM的特色之一，我觉得非常好用。你说的这种模式的开源太多了，尤其是轻论坛，简直就是泛滥，什么语言的都有，SYM好看，你找一个轻论坛来套SYM的模板就可以。两种都用过之后，你就会选择SYM，它很优秀。

**Comment by 88250** [comment]
你好啊~ 多谢反馈

1. Sym 里的标签其实是一个自下向上进行的分类方式，由标签聚合出领域来进行分类，这个设计我觉得更灵活
2. 标签对于浏览者不会产生多少干扰吧，对于发布者也非必填项，这两点对于使用体验来说我觉得没有多大问题
3. 此刻的设计其实也很好玩的，而且可以看一下大家都在干嘛，可以追踪别人的足迹哦
4. 搜索功能是必须的啊，不然怎么找到对自己有用的帖子呢？

我觉得你还没有了解到 Sym，请再好好使用一下就能体会到啦 :grapes: 

这个 issue 我先关闭了，有更多需要讨论的请到[黑客派](https://hacpai.com)上进行，再次你的反馈！
