### ISSUE TITLE
不停的发这些垃圾邮件有意思吗？

### ISSUE THREAD

**Issue by justjavac** [b3log/symphony#192]
![image](https://cloud.githubusercontent.com/assets/359395/15278936/839da27e-1b51-11e6-8038-3e83cda63fc1.png)

**Comment by justjavac** [comment]
![](http://i3.buimg.com/2a882dab74e038b6.png)

**Comment by 88250** [comment]
你好，我是想邀请你加入这个开源组织，如果打扰到了请原谅 :grapes:
