### ISSUE TITLE
为什么maven编译的时候就出错了

### ISSUE THREAD

**Issue by rushui2016** [b3log/symphony#195]
Plugin org.b3log:maven-min-plugin:1.0.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.b3log:maven-min-plugin:jar:1.0.0: Could not transfer artifact org.b3log:maven-min-plugin:pom:1.0.0 from/to central (http://repo1.maven.org/maven2): Connect to repo1.maven.org:80 [repo1.maven.org/23.235.47.209] failed: Connection timed out: connect -> [Help 1]

**Comment by 88250** [comment]
你连 maven 中央库超时了，可能是网络方面的原因吧~
