### ISSUE TITLE
QQ 登录

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#204]
开始实现第三方登录，首个对接的开放平台是 [QQ 互联](http://connect.qq.com) ，后续会继续 #114 。

### 设计

1. 在注册/登录表单页面添加`QQ 登录`按钮
2. 用户点击`QQ 登录`按按钮后弹出 QQ 登录小窗，用户登录授权成功后跳转回 Sym 的“账号绑定”页面
3. “账号绑定”页面表单有 3 个字段，用户填完提交后生成/绑定 Sym 账号
   - 用户名（规则同以前，只能使用字符或者数字，必填）
   - 昵称（默认使用 QQ 登录返回 info 中的昵称填充，非必填）
   -  密码（必填）
4. 此时用户已经处于登录状态，后续可以使用用户名登录或者继续使用 QQ 登录

### 实现

- 使用 QQ 互联提供的 [JS SDK](http://wiki.connect.qq.com/js_sdk%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)
- 由于邮箱是账号结构必须的，所以在生成（非绑定）账号时实现上需要使用`Username@sym.b3log.org`来进行默认填充，后续需要添加用户端的“更新绑定邮箱”功能
- 处理使用邀请码注册情况

**Comment by linkerlin** [comment]
个人觉得新浪微博和微信可能更加重要点。

**Comment by codepython** [comment]
第三方登录是不是集成一个sdk就行了？

**Comment by 88250** [comment]
@codepython 还在考虑，目前优先接入第三方登录可能是微信。

**Comment by ibguy** [comment]
建议优先接入qq登录，毕竟微信很多个人网站很难做到
微信都要认证的
@88250

**Comment by 88250** [comment]
@ibguy 收到，谢谢提醒

**Comment by yangzhengnan** [comment]
建议支持微信呢，例如关注社区官方微信公众号后，即可正常发文，提问题
