### ISSUE TITLE
可配置登录后才能浏览

### ISSUE THREAD

**Issue by MuChan** [b3log/symphony#205]
1、不开放注册后，主域名hacpai.com 访问，没有登陆拦截跳转到登陆页面，只有登陆了才跳转到现在的首页。
2、其他页面可以先和目前一样不用拦截，比如帖子页面，不用拦截，是否显示可以由发帖人发帖或评论的时候设置，比如设置打赏才能查看。

**Comment by 88250** [comment]
多谢建议，会考虑加入一个后台配置项，用来设置“是否登录后才能浏览”，另外会根据 UA 来识别搜索引擎爬虫，如果是爬虫请求则默认不拦截。

这个特性下周会找时间进行实现。

**Comment by 88250** [comment]
拖了快一个月了，呃。

这周末搞定 :joy_cat:
