### ISSUE TITLE
关于博客发表文章同步到社区时积分并未扣除问题

### ISSUE THREAD

**Issue by TiSongWen** [b3log/symphony#208]
在 solo 博客中提交一篇文章，但是 在社区中的积分 并未扣除对应的分数。

> 还有一个小小的疑问：为什么积分的显示是 十六进制呢？^ ^。

**Comment by 88250** [comment]
从博客过来的文章都不会扣积分的，这是特意的。

黑客积分的显示是十六进制，画家积分的显示是颜色 :smile:
