### ISSUE TITLE
emoji 列表定制

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#210]
统计常用的emoji表情（个人，或者所有）作为默认列表，如此在发帖的时候能够更容易添加表情
更进一步，能够在个人设置处自定义默认列表的显示

**Comment by ZephyrJung** [comment]
拟用java代码生成html字符串来展现设置页面表情列表，可能代码如下：

>  final String emojiHtml="<table><tr><td onclick='alert(1);'><img style='width:25px;height:25px;' src='/emoji/graphics/emojis/bowtie.png'></td></tr></table>"
前台使用${emojiHtml}直接插入html，切换表情类型时只需要重新获取下emojiHtml即可，不知D大意下如何 @88250

**Comment by 88250** [comment]
没太明白..只是觉得这样做的话安全方面得做很多处理..

**Comment by 88250** [comment]
突然发现，这个是 1.5 的 issue，应该关闭才对。我先关闭这个 issue 了，如果要做就单独开一个 issue 继续讨论~
