### ISSUE TITLE
关于社区邀请机制

### ISSUE THREAD

**Issue by VirtualPier** [b3log/symphony#214]
我认为邀请机制应该分为两种
1. 用户邀请--链接形式
2.邀请码

目前的邀请机制感觉挺蛋疼的

**Comment by 88250** [comment]
谢谢反馈！

用户邀请链接现在也是有的，通过邀请链接邀请的话主要是可以获得额外积分。不过即使通过邀请链接，
也是需要邀请码的。

后面可能会考虑让用户自己通过积分兑换邀请码。

**Comment by linkerlin** [comment]
不如直接卖邀请码，比如捐款10块以上就可以或一个邀请码。

**Comment by 88250** [comment]
@linkerlin 卖的话我担心给人的感觉会变味。

**Comment by 88250** [comment]
https://github.com/b3log/symphony/issues/235
