### ISSUE TITLE
打赏区无法隐藏

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#219]
不小心点开后就无法隐藏，刷新也一样
建议添加隐藏功能或者在刷新本页面的时候恢复成原状

**Comment by ZephyrJung** [comment]
火狐浏览器下刷新无法隐藏，IE可以

**Comment by 88250** [comment]
目前主要是保证 Chrome 下的体验，其他浏览器下的体验只能慢慢改进了。

@Vanessa219

**Comment by ZephyrJung** [comment]
已经无法复现，大概是发生了什么神秘的事情
