### ISSUE TITLE
帖子优选

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#229]
类似于贴吧的加精，并且设置单独的精品区，如此可以将高质量内容的帖子汇总，方便初入论坛的人查看，高质量的帖子是留住访问者的重要原因，访问者在短时间内无法在很多帖子中筛选出真正需要的帖子，论坛目前所分的热门类只与热度相关，与帖子内容关系不大（质量贴可能只讲技术，以至于吸引到的回复比较少）

**Comment by Vanessa219** [comment]
加精后可以每月或每周出一期。就像知乎每周都会推一些文章发邮件给我一样。那样感觉还不错。

**Comment by 88250** [comment]
@Vanessa219 #44
