### ISSUE TITLE
面包屑导航

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#230]
http://cdc.tencent.com/2009/07/06/%E9%9D%A2%E5%8C%85%E5%B1%91%E8%AE%BE%E8%AE%A1/

**Comment by Vanessa219** [comment]
<img width="1279" alt="qq20161029-0 2x" src="https://cloud.githubusercontent.com/assets/970828/19814607/774b83fe-9d71-11e6-8fb3-99c3dcde285c.png">
目前是这样子设计的，整个社区需要保持简洁的风格。面包屑这样使用在大量分级内容或偏引导性功能的设计就不引入了。
