### ISSUE TITLE
在浏览帖子时实时显示浏览该帖的用户

### ISSUE THREAD

**Issue by billho** [b3log/symphony#236]
如题，比如说我在看《文件上传的问题》这篇文章的时候，直接将同时在看这篇文章的人也显示再里面。

**Comment by 88250** [comment]
收到，放到后面一点考虑..

**Comment by BigPanc** [comment]
建议增加多少人关注或者推荐这个帖子的按钮，或者显示小提示

**Comment by 88250** [comment]
@BigPanc 现在已经有了 :)

**Comment by 88250** [comment]
可能会涉及到隐私，暂时作罢。
