### ISSUE TITLE
添加新活动 - 小游戏【贪吃蛇】

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#239]
目前活动比较单调，建议添加小游戏作为新活动，一来可以通过游戏的方式挣取论坛积分，二来可以让用户稍作放松，三来跟随一下H5游戏的潮流~

**Comment by ZephyrJung** [comment]
关于前端游戏的分数控制（避免修改请求参数刷分现象）
目前有个想法是：以贪吃蛇为例，吃到苹果时，向后台发出加密通知，后台计分，结束时再发出通知，后台返回分数

**Comment by ZephyrJung** [comment]
防止重复提交：
开始游戏时生成随机令牌，并且生成随机位置，反馈到前端，积分根据随机数插入到令牌中，提交到后台，后台获取分数。
防止篡改积分：
录制行动脚本，每次吃到苹果时上传后台检验（需要上传上次苹果的位置），计算根据脚本是否能达到苹果位置。一旦校验失败，则为非法提交。

**Comment by 88250** [comment]
先简单粗暴实现积分：

1. 每局开始 20 积分
2. 吃一个苹果 1 积分，游戏结束时提交
3. 最高奖励设置在 50 积分

**Comment by ZephyrJung** [comment]
建议积分策略，两种办法：
一：每天第一局有积分奖励，开局扣除积分。
二：每天随机某一局有积分奖励，不扣除积分。
奖励之后，可以随意玩耍刷榜，但无积分奖励了

**Comment by 88250** [comment]
又加入一种积分策略：算平均分，0 平均分的话算 20 一局。这样比较动态，对低手不会造成太大伤害，同时也可以对高手产生一定压力。

**Comment by ZephyrJung** [comment]
@88250 在游戏结束提示上加个结果保存功能怎么样，直接保存结果图到某个地方，或者生成文件让用户保存，这样可以用来晒

**Comment by 88250** [comment]
不知道能不能用 JS 来截图，有空研究下。

**Comment by ZephyrJung** [comment]
OK，交给我吧（生怕不说你就搞定了。。）
ps，如果有必要还可以减小格子粒度0.0

**Comment by 88250** [comment]
似乎不用截图，直接 Canvas 转 base64 就好啦~

**Comment by ZephyrJung** [comment]
canvas.toDataURL() 我mark一下免得忘了

**Comment by 88250** [comment]
暂告一段落，close 了。
