### ISSUE TITLE
专题版块

### ISSUE THREAD

**Issue by huanliuliu** [b3log/symphony#246]
### 专题
 
   * 场景
         
        1. 社交群：每周一到周六晚上23点，会有微信群小助手进行分享文章，文章来
源一方面是网络摘抄，另一方面来自社交渠道征集。（不足，容易刷屏）

        2. 每隔一段时间，会进行关于某一领域的专题分享，持续时间一到两个月，涉及若干人。期间，会有一些优质的内容，也会鼓励学员分享一些心得体会，经过肯定后，会在一定程度的加分。
        
    * 功能
      
        1. 新建专题，包括设置管理员，投稿方式，以及是否需要审核。
其中管理员可以对文章内容进行人已操作。
        2. 用户创建文章，进行投稿。

**Comment by 88250** [comment]
请参考 #252
