### ISSUE TITLE
我的优选

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#252]
目前优选只是管理员对单贴进行标识

建议改成用户自建集合，比如类似一些知识社区的专题、音乐社区的歌单一样。通过用户的维度来加工和发掘内容价值。

基本功能：
用户自建优选集合，一个集合多篇文章。
集合内容来源于社区内帖子的筛选。
非创建者可投稿，需由创建用户审核。

高级功能：
优选关注、集合榜单、集合订阅

**Comment by 88250** [comment]
感谢提议，和 #246 思路好像差不多，后续会进行实现。

**Comment by luhua** [comment]
把收藏和现有的优选整合：
https://hacpai.com/article/1476431543803

**Comment by 88250** [comment]
暂时不考虑实现了，感谢提议！
