### ISSUE TITLE
通用活动模板

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#253]
Inspired by豆瓣
即发布一个主题，让用户参与发表（图片、文字）从中选出人气最高的进行奖励，可以指定一次活动的持续时间

**Comment by 88250** [comment]
具体来个例子。

**Comment by ZephyrJung** [comment]
https://www.douban.com/online/ 这是豆瓣活动的地址。之前参加过一个古诗三句半的活动，发上根据活动要求截的图后（红豆生南国，春来发几枝，愿君多采撷，好吃），其他人可以评论，可以点赞点踩之类的，他的活动形式都是一样的，只不过主题不同

**Comment by 88250** [comment]
了解了，这个功能还是蛮有意思的，先可以研究一下怎么实现最简单。

**Comment by ZephyrJung** [comment]
与D大讨论后，认为次功能与当前贴标签的文章没有什么区别，故而关闭，由此提出新的issue

**Comment by 88250** [comment]
多谢讨论了！

**Comment by ZephyrJung** [comment]
b3log群内发起过几次话题讨论，感觉没有活动让大家参与记录十分可惜，仔细想想，各个用户参与同一个活动贴发布内容，与用户发各个帖子贴上同一个标签，在后台存储上或许相近甚至可以一致，但是在展示上还是有很大区别，而这种展示方式正是活动功能的精髓所在，感觉还是有意义的，故而reopen，留待再考虑

**Comment by 88250** [comment]
还是关闭吧，没有找到很好的引爆点。
