### ISSUE TITLE
编辑器中的 HTML 转义字符处理问题

### ISSUE THREAD

**Issue by billho** [b3log/symphony#254]
如下图，当原文中有 & nbsp; & amp; 等转义符时，再次进入MarkDown编辑时，转义字符会被直接转义成空格和&号。
此时如果什么都不改直接保存时，原文中的转义字符却不会还原。
![image](https://cloud.githubusercontent.com/assets/7029336/17960910/4e192068-6adb-11e6-8c32-dcfa1cef8056.png)

![image](https://cloud.githubusercontent.com/assets/7029336/17960967/a1bef40e-6adb-11e6-8e09-81c9e0f71b88.png)

**Comment by 88250** [comment]
代码的话要用 MD 语法哦

**Comment by billho** [comment]
@88250 已用了，正是代码块里面出现的问题。你可以发个帖子反复改改试试

**Comment by 88250** [comment]
好的，等会看下。

**Comment by 88250** [comment]
确实这个问题，稍后会修复。

**Comment by zh-h** [comment]
捂脸，转义和反转义混乱了
