### ISSUE TITLE
电话沟通

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#256]
## 背景

浏览者在看帖子后可能需要和贴主进行沟通，普通方式就是回帖，但有时回帖并不即时高效，贴主不一定能够即时看到，而且回帖打字比较累，沟通效率较低。（回帖时用离线语音可以提升一定效率）

电话沟通非常高效，如果能在保护用户隐私的前提下建立通话，那问题就迎刃而解了。另一方面，论坛最终的目的是帮助用户进行交流，所以引入更高效的沟通方式对于用户来说是非常有价值的。
### 原理

我们引入网页回拨的方式进行通话，回拨的大致工作原理请参考[呼叫中心架构设计](https://hacpai.com/article/1468846228337)。
### 功能点

在使用之前，用户需要通过短信验证来绑定手机，只有当贴主和浏览者都绑定过手机，帖子页面的 toolbar 上才会出现电话的图标，点击后即可发起回拨呼叫（先呼浏览者）。另外，用户主页也需要增加一个回拨图标，方便直接联系某用户。

用户设置除了绑定手机，还需要有个开关来设置是否开启回拨，如果不开启的话该用户所发的帖子也不会出现电话图标，并且自己也是不能发起回拨的。
### 号码透传和录音
- 不设置主叫显号，被叫固定透传主叫号码
- 不进行录音
## 积分

回拨的费用较高（一次回拨相当于两路通话），需要根据通话状态、通话时长来计算积分，在通话结束后扣除回拨发起者相应的积分。
## 应用场景

开头部分提到的讨论问题的场景可能不是太适合。电话更适合的场景应该是 B2C 的，结合同城功能就可以非常方便地进行招聘。用户自己可以选择是否处于”待雇佣”状态作为回拨开关。

另外，除了招聘，也可以是二手买卖，方便询价等私密性强的交易。

**Comment by billho** [comment]
我认为这不是个好的主意。
首先，试想一个用户如果因为发了一个好帖子，而一天之类收到好几十个电话的感受，难以容忍，估计他以后发帖都不会开启这个功能了；（这里还未考虑骚扰电话）
其次，电话沟通固然是快与便捷，但是不利于内容沉淀，楼主回答过的问题不能为其他人所复用，仍需继续回；
再者，电话功能可能会引起论坛这个产品功能性偏移。论坛重点在于内容+轻社交，讲求开放共享；电话则重在通讯，私密性强。强要将这两个东西做到一起，难以找到权衡点。

**Comment by billho** [comment]
相对于电话，我认为IM反而会好一点。

**Comment by 88250** [comment]
@billho 

1. 提高使用这个功能的门槛，比如需要积分达到 3K 以上才能使用。这样可以避免很多骚扰的可能性，而积分较高的用户我们可以认为符合社区价值观，所以应该为这些用户提供更多的功能
2. 考虑过对通话进行录音，并且录音会上传到帖子中作为离线语音，更进一步，可能会使用语音转文本的第三方服务来进行文本化。这个点上面我想也是符合未来趋势的
3. 目前 Sym 已经完成了论坛的功能了，打算在其他功能性上面进行一些创新

还需要思考，欢迎继续碰撞。

**Comment by luhua** [comment]
不反对，也不建议加这些功能。。。
因为我觉得把社区本身主要的功能和体验打磨好才是重点
社区其实好多东西都可以再进一步
比如权限管理
比如用户级别、荣誉认证和激励等这些社区生态体系
比如内容订阅推送、回复对话等体验优化

**Comment by 88250** [comment]
关闭没啥卵用的想法。
