### ISSUE TITLE
新增帖子类型-记录贴

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#257]
与普通帖子其他部分相同，正文处不再是一片大文章，而是一段一段的记录，可以持续更新
inspired by：
公司技术群时不时会指出代码中的问题并进行讲解，我认为很有记录的价值，本来想写在笔记本中，但觉得这样似乎既不美观，有不方便分享。
正文处大致像solo的博客缩略列表，但是更小一点

**Comment by ZephyrJung** [comment]
此功能也可以在活动issue中作为一个长期活动，以点赞排序，可以看到有价值的记录

**Comment by billho** [comment]
这个点子不错！

**Comment by 88250** [comment]
记录、想法的内容还是适合放在个人笔记上，发出来的话会显得比较乱。我关闭这个提议了，有需要讨论的随时打开。
