### ISSUE TITLE
回帖编辑改进

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#260]
现在的编辑器是在回帖区顶部（实时浏览模式）或者回帖区底部（传统浏览模式），这样如果用户浏览到中间想回复某条回帖时就会发生跳转，导致看不到这条回帖。

解决这个不好的体验有两个方式：

1. 在想回复的回帖下方插入编辑器（知乎、OSC 等）：这个方式只适合编辑器很简洁的产品，比如就是纯文本框。但 Sym 的编辑器较复杂，比较占显示位置，所以这个方式不可取
2. 使用固定位置的编辑器，当用户点回复按钮时从底部浮出：这个方式即不会造成回帖区 UI 的变化，也不影响用户继续滚动回帖区后回帖（不用滑回去找原回帖），但这个方式比较挑战用户习惯

综上，采用方式 2 进行实现 :smile:

**Comment by ZephyrJung** [comment]
本来想说插入一个简单的编辑器作为回帖更简单呢，不过2方式看起来蛮炫酷的
