### ISSUE TITLE
快捷键支持

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#265]
用于方便跳转到经常浏览的页面，或者弹出一个控制台，可以输入一些指令，比如：
goto:new //跳转到最新帖子标签页
goto:hot //热门
goto:setting //设置
程序员的懒已经到了骨子里，动动鼠标什么的，不够炫酷

**Comment by 88250** [comment]
用快捷键更方便，准备参考 Google Inbox 的设置：

![image](https://cloud.githubusercontent.com/assets/873584/18480924/01ae5ed2-7a0d-11e6-9196-9826375d87c0.png)

**Comment by ZephyrJung** [comment]
其实我觉得能调出个控制台然后输入指令更酷，实现起来也会更容易吧

**Comment by 88250** [comment]
以方便为主，cool 为辅.... 比较复杂的可以用指令。

**Comment by 88250** [comment]
还需要加入设置开关，默认关闭。

@Vanessa219
