### ISSUE TITLE
首页自定义模块

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#267]
通过拖拽的方式调整首页的模块显示，理想的情况是可以自行划分首页的布局（每个模块显示的大小，位置等）
第一步我觉得可以先做成布局不变，但是可以调整五块区域的顺序，内容（六块内容：最新，最热，优选，此刻，赞助商，发帖（赞助商的位置或可固定））

**Comment by 88250** [comment]
我关闭这个 issue 了，社区系统不是主要强调工具/功能属性，所以暂时不考虑这么灵活的 UI 布局特性。
