### ISSUE TITLE
关注提醒

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#271]
对于关注的标签，当标签下有新帖发出时，也应当进行提醒

**Comment by 88250** [comment]
当初设计这个的时候主要担心标签下面新帖太多，会造成很多提醒。目前看来似乎完全没有这个问题，因为论坛不热 😂 

可以考虑加一下，等有空我来弄吧。

**Comment by ZephyrJung** [comment]
可以在提醒处只表明有更新而无需对于每个新帖都进行提醒

**Comment by 88250** [comment]
发现有个不好把握的点，就是标签是可以更新的，所以通知在第一时间发的话会有些问题，看来这个 issue 得延后再考虑了。

**Comment by ZephyrJung** [comment]
大概指点一下我学习学习？

**Comment by 88250** [comment]
可以看下什么地方使用了 `NotificationMgmtService`

**Comment by 88250** [comment]
通知用来做这个不科学，先关闭了。
