### ISSUE TITLE
新搭建的bug

### ISSUE THREAD

**Issue by yongsudehanzi** [b3log/symphony#272]
环境：chrome
date：2016/9/9
问题：
          
![default](https://cloud.githubusercontent.com/assets/14308649/18378698/0b1c2950-76a1-11e6-9862-86e3594398be.jpg)

**Comment by ZephyrJung** [comment]
积分十六进制显示是有意而为之
右上角那个似乎也不是bug，你要不看看是不是哪没配置好？

**Comment by yongsudehanzi** [comment]
好的
错误原因是默认的upload目录不能访问，问题不大

**Comment by 88250** [comment]
可以在 sym.props 里面修改一下 upload 目录的路径。

**Comment by 88250** [comment]
没有其他问题的话我关闭这个 issue 了 :-p
