### ISSUE TITLE
顶部 Banner 展位

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#280]
最好位于常见地方，有公告的时候显示，没有的时候隐藏即可
重点是，每次更新时应当进行公告，公告中可附带更新说明帖子链接
对于更新后的常见问题，指出解决办法

**Comment by 88250** [comment]
![i9 w_x w5tee d gzx7i1sg](https://cloud.githubusercontent.com/assets/873584/21455885/d7519cca-c95e-11e6-839f-bce9e85b57a2.png)

类似这样 @Vanessa219
