### ISSUE TITLE
改进移动端页面翻页

### ISSUE THREAD

**Issue by zh-h** [b3log/symphony#286]
换成左边上一页，右边下一页，中间是弹出列表跳转

**Comment by 88250** [comment]
有类似应用可以参考么？截个图

**Comment by zh-h** [comment]
@88250 
![www chiphell com-forum php-mod forumdisplay fid 188 page 3 mobile yes iphone 5](https://cloud.githubusercontent.com/assets/13273151/18736016/3f2f10ea-80b5-11e6-8fb0-796b4ded3588.png)

**Comment by 88250** [comment]
收到，看情况吧，这个优先级不高，你要能 PR 一发也是极好的 😄

**Comment by zh-h** [comment]
争取这周来一发

**Comment by 88250** [comment]
@zh-h 然而这周已经过去了 😂

**Comment by zh-h** [comment]
Javascript 代码加到哪个文件好

**Comment by 88250** [comment]
单独弄个叫 mobile.js 的吧，大致完成后你提交就行，剩下的 @Vanessa219 来帮忙继续完善。
