### ISSUE TITLE
后台管理用户相关字段补全

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#287]
自我标签

分页每页条目
头像浏览模式
启用 Web 通知
订阅邮件
启用键盘快捷键 
设置常用表情

位置
 
公开帖子列表
公开回帖列表
公开关注用户列表
公开关注标签列表
公开收藏帖子列表
公开粉丝列表
公开积分列表
公开在线状态
公开 UA 信息
公开行踪到此刻中
公开链接熔炉
参与财富排行
参与消费排行

**Comment by 88250** [comment]
又补充了一些，另外`设置常用表情`这个暂时不实现了。

**Comment by ZephyrJung** [comment]
其实没太明白这个功能干啥的，啥叫相关字段补全？

**Comment by 88250** [comment]
@ZephyrJung  管理后台的，缺失了很多后来加的用户字段。
