### ISSUE TITLE
全屏写作－分屏模式

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#290]
就是将编辑窗口最大化后，分成左右两屏，左侧编辑，右侧实时显示markdown效果
如此不仅便于格式调整，同时有助于写长文

**Comment by 88250** [comment]
前两天 @Vanessa219 才刚把全屏模式去了，这个 issue 我们以后再过一下，目前优先级很低。

**Comment by ZephyrJung** [comment]
额，我以为是去了回复框的全屏，那个是真没用
但是写文档的时候有全屏会很方便的（参考简书）
不过确实不急，如果需要可以用别的markdown先写好：P

**Comment by ZephyrJung** [comment]
不知道这种方式是不是更容易实现：切换到预览时，滚动条滚动到某个地方，再切回编辑模式时，滚动条同步？@88250

**Comment by 88250** [comment]
滚动条？

**Comment by TiSongWen** [comment]
似乎是说 ：预览模式滚动位置 和编辑模式的 光标位置是同步的。

**Comment by 88250** [comment]
@TiSongWen 嗯，明白了。这个要看 @Vanessa219 什么时候有空了.... 源码视图和预览视图要完全一致的话处理起来估计麻烦。

**Comment by ZephyrJung** [comment]
辛苦D大V大了，不急:p

**Comment by Vanessa219** [comment]
没有实现滚动同步的。😄
