### ISSUE TITLE
帖子编辑器显示关注的标签

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#293]
一般关注的标签就是常用的标签（我认为……）
放置在编辑去标签选择处，更容易选择
这个我就这么一说，可以忽略……我大概是懒到了极致

**Comment by 88250** [comment]
这个优化确实有意义，是应该加一个“我关注的”栏，方便选择：

![image](https://cloud.githubusercontent.com/assets/873584/25283679/25961a06-26e7-11e7-85f6-947811c56ceb.png)
