### ISSUE TITLE
发布帖子前检查标题重复

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#296]
填完标题，在没有写内容之前，自动检测：

1、标题重复：影响发布

如标题重复，提示用户重复帖子和重复链接。
用户可以先去看一下，参考后，再继续发帖。

2、类似帖子：不影响发布

可以检测类似的帖子，并提示用户。
方便用户参考、引用， 写出更好的内容。

**Comment by 88250** [comment]
【类似帖子】这个估计做不到，以搜索来做的话不准确。
