### ISSUE TITLE
帖子列表多种排序

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#300]
### 最新帖子列表

* 默认（按发布时间降序）
* 热议（按回帖数降序）
* 好评（按评分降序）
* 最近回帖（按回帖时间降序）

### 标签-帖子列表

* 同最新帖子列表
* 优选（只显示该标签下的优先贴，按发布时间降序）

领域帖子列表不进行排序。

**Comment by aqqwiyth** [comment]
最近也在做商品相关的推荐排序. 建议把各种维度拿出来打分排序 . 然后z唉看数据是否合理. 





比如用电商的视觉看待(所谓的综合排序)
发布时间==上架时间     占比xx%
热议数量==购买数量     占比xx%
内容质量==运营喜欢就多给点
评论质量==购买后的评分
类目加权                (特殊类目加分)
用户加权                (VIP客户发布的商品)
管理员隐藏加权     (置顶几小时)

**Comment by meikaiyipian** [comment]
这个是哪里的，首页吗，还是最新标签下的呢？

**Comment by 88250** [comment]
@meikaiyipian 最新以及标签下的

**Comment by 88250** [comment]
@aqqwiyth 有道理，这样动态性更强、更灵活一些。但是太复杂，懒得改了，后期考虑 😂

**Comment by meikaiyipian** [comment]
@88250 最新下面的话，个人感觉论坛顶部上面 最新 旁边已经有 热门 和 优选 标签了，还需要再变动吗？
至于排序的话就如上面二楼仁兄所说，给帖子加上各种维度，但这方面太复杂了，每个论坛也不一样，需要一段时间的探索

**Comment by luhua** [comment]
我觉得应该有个回复，如下：
- 默认（按发布时间降序）
- 回复（按回复时间降序）
- 热议（按回帖数降序）
- 好评（按评分降序）

另外，这里是不是可以把优选加进来？ 则：
**可选项（只显示）：**
- 全部（全部帖子）
- 优选（此标签下的优选帖子）
- 原创（这个可能要增加发帖项）
- 转载（这个可能要增加发帖项：出处以及来源地址）

**排序项目**
- 默认（按发布时间降序）
- 回复（按回复时间降序）
- 热议（按回帖数降序）
- 好评（按评分降序）

**Comment by 88250** [comment]
@luhua 谢谢建议。标签-帖子列表增加优选，其他的以后再考虑了。

**Comment by 88250** [comment]
@meikaiyipian 最新列表不加 优选 ，热门列表不加任何排序。

**Comment by luhua** [comment]
要不要增加一个最新回复？ 这样可以看到大家正在讨论那个帖子，也比较方便参与进来。

**Comment by 88250** [comment]
@luhua 好的，加。
