### ISSUE TITLE
后台帖子管理增强

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#302]
后台帖子管理增强：
- 根据帖子ID、作者、关键字多条件准确查询帖子
- 批量选择、删除帖子
  ![123](https://cloud.githubusercontent.com/assets/3127313/19299425/d0071f3c-9086-11e6-83a3-8b860a49e672.png)

**Comment by tom798** [comment]
建议帖子维护列表，增加序号

**Comment by 88250** [comment]
目前没有达到那么大体量的用 Sym 建的社区，管理上我觉得并不耗费太大精力，暂时没必要做后台太强的功能。

序号后面会加。
