### ISSUE TITLE
关于图片上传是否拥有压缩功能？

### ISSUE THREAD

**Issue by TiSongWen** [b3log/symphony#304]
文章发表时的图片，服务器是否会自动压缩呢？

**Comment by 88250** [comment]
目前无论是上传到七牛还是本地服务器，都没有压缩功能。

**Comment by TiSongWen** [comment]
那图片压缩的功能是否需要加入呢？^ ^

**Comment by 88250** [comment]
一般是上传的时候压缩还是浏览的时候压缩？

**Comment by TiSongWen** [comment]
我是担心会不会因为 用户上传了一些较大的图片而造成再次访问服务器时造成较大的压力。嘿嘿～ 只是一个小小的问题哈。

**Comment by 88250** [comment]
哦，文件上传有大小限制的，可以在 sym.props 配置文件中设置。

**Comment by TiSongWen** [comment]
那从您的角度来看，服务器自动压缩图片的功能是否在一个Web项目中有必要添加呢？

**Comment by 88250** [comment]
我的想法是原图必须保存，显示的时候可以设置默认质量。

**Comment by TiSongWen** [comment]
恩恩。谢谢您的解答哦！！！

**Comment by 88250** [comment]
客气客气，欢迎多来论坛看看 https://hacpai.com

这个 issue 我关闭了 :)
