### ISSUE TITLE
弹出按钮功能

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#305]
帖子浏览右下角的回复显示按钮和回到顶上的按钮很好看，希望回复提交按钮以及匿名之类的功能也集成到这里，避免操作不流畅，到处点
 可参考https://bguzmanrio.github.io/vanilla-fancy-selector/
这个按钮可以固定到页面右下角，在不同的页面上显示不同的功能
比如首页时，此处可以引导到：发帖、关注标签、关注人、收藏页面（可以与右上角个人那里做个分类，各自承担一部分）
浏览帖子时，这里可以：回到顶部，回复本帖，开启匿名
弹出式的按钮应该可以做到很智能吧，不过鉴于现有功能，或许稍作浏览时的效果即可

**Comment by 88250** [comment]
现在稍微改版了一下，右下角按钮太过于花哨，准备去除。这个 issue 关闭了哦，多谢建议 😺 

@Vanessa219
