### ISSUE TITLE
部署成功，但是注册验证码出不来

### ISSUE THREAD

**Issue by linkerlin** [b3log/symphony#308]
Request URL:http://www.tujie8.net/captcha
Request Method:GET
Status Code:404 Not Found
Remote Address:139.59.195.191:80
Response Headers
view source
Cache-Control:must-revalidate,no-cache,no-store
Connection:keep-alive
Content-Encoding:gzip
Content-Type:text/html;charset=iso-8859-1
Date:Mon, 17 Oct 2016 15:08:04 GMT
Server:nginx/1.10.0 (Ubuntu)
Transfer-Encoding:chunked
Request Headers
view source
Accept:image/webp,image/*,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6,zh-TW;q=0.4
Cache-Control:no-cache
Connection:keep-alive
Host:www.tujie8.net
Pragma:no-cache
Referer:http://www.tujie8.net/symphony/register?goto=http%3A%2F%2Fwww.tujie8.net%2Fsymphony%2F
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

[链接](http://www.tujie8.net/symphony/register?goto=http%3A%2F%2Fwww.tujie8.net%2Fsymphony%2F)

**Comment by 88250** [comment]
看似是因为 #309 引起的，这个 issue 先关闭。
