### ISSUE TITLE
注册时支持手机号和短信验证

### ISSUE THREAD

**Issue by linkerlin** [b3log/symphony#312]
我发现一个 短信API接入也蛮简单的：
https://www.juhe.cn/docs/api/id/54

**Comment by 88250** [comment]
技术接入到不是问题，关键是社区类型用手机号好像不大合适。

后期再考虑，可以和特性 #256 一起来做。无论如何，谢谢提议！

**Comment by 88250** [comment]
目前商业版已经支持第三方登录，那样更方便，手机绑定作为其他功能的前置也已经实现。
