### ISSUE TITLE
快捷键提示

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#321]
为每个可以用快捷键代替的按钮添加快捷键说明
方便记忆，看得多了自然就会了

**Comment by 88250** [comment]
那是不是要默认启用快捷键？

**Comment by ZephyrJung** [comment]
不用，让用户知道有这个东西就行

**Comment by 88250** [comment]
然后按了没用这不是忽悠人么 😂

**Comment by ZephyrJung** [comment]
所以我其实想过用弹出式的按钮切换快捷键开关……但是这个issue不是关了嘛，所以或许可以考虑别的方式
总之，加上提示才能让人迅速掌握快捷键0.0

**Comment by Vanessa219** [comment]
@ZephyrJung 加了个小贴士。快捷键还没想好怎么去提醒用户

**Comment by ZephyrJung** [comment]
待我体验体验小贴士 :smile:

**Comment by 88250** [comment]
体验结果如何？

**Comment by 88250** [comment]
我关闭这个 issue 了。
