### ISSUE TITLE
功能级权限

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#337]
## 功能级权限

使用 RBAC 模型实现功能级权限管理，主要解决“某用户是否能够使用某功能”的问题。默认内建 6 种角色 #358 ，待信任系统  #259 完成后会按用户等级来自动进行用户的角色变迁。

管理员可以为每种角色赋予/撤销一些权限，考虑到社区系统业务不会太过复杂，所以不准备加入用户或者角色的树形模型，即不需要“用户组”/“角色组”这样的模型。如果要复用权限，就单独配置新的角色，不考虑权限继承；另外，也不考虑用户分配多个角色，一个用户同时只能是一种角色。

### 常规功能权限，类别 `0`

* 发帖 `commonAddArticle`
* 匿名发帖 `commonAddArticleAnonymous`
* 更新帖子 `commonUpdateArticle`
* 回帖 `commonAddComment`
* 匿名回帖 `commonAddCommentAnonymous`
* 更新回帖 `commonUpdateComment`
* 置顶帖子 `commonStickArticle`
* 感谢帖子 `commonThankArticle`
* 点赞帖子 `commonGoodArticle`
* 点踩帖子 `commonBadArticle`
* 收藏帖子 `commonFollowArticle`
* 查看帖子编辑历史 `commonViewArticleHistory`
* 查看回帖编辑历史 `commonViewCommentHistory`
* 感谢回帖 `commonThankComment`
* 点赞回帖 `commonGoodComment`
* 点踩回帖 `commonBadComment`
* 艾特用户 `commonAtUser`
* 艾特参与者 `commonAtParticipants`
* 积分兑换邀请码 `commonExchangeIC`
* 使用邀请链接 `commonUseIL`

### 用户管理权限，类别 `1`

* 添加用户 `userAddUser`
* 修改用户基本数据、状态 `userUpdateUserBasic`
* 修改用户邮箱/用户名 `userUpdateUserAdvanced`
* 给用户充值积分 `userAddPoint`
* 给用户兑换积分 `userExchangePoint`
* 给用户违规扣除积分 `userDeductPoint`

### 帖子管理权限，类别 `2`

* 添加帖子 `articleAddArticle`
* 修改帖子基本数据、状态 `articleUpdateArticleBasic`
* 置顶帖子 `articleStickArticle`
* 取消置顶帖子 `articleCancelStickArticle`
* 重建帖子搜索索引 `articleReindexArticle`
* 重建所有帖子搜索索引 `articleReindexArticles`
* 删除帖子 `articleRemoveArticle`

### 回帖管理权限，类别 `3`

* 修改回帖基本数据、状态 `commentUpdateCommentBasic`
* 删除回帖 `commentRemoveComment`

### 领域管理权限，类别 `4`

* 添加领域 `domainAddDomain`
* 添加领域标签 `domainAddDomainTag`
* 移除领域标签 `domainRemoveDomainTag`
* 修改领域基本数据、状态 `domainUpdateDomainBasic`
* 删除领域 `domainRemoveDomain`

### 标签管理权限，类别 `5`

* 修改标签基本数据、状态 `tagUpdateTagBasic`

### 保留词管理权限，类别 `6`

* 添加保留词 `rwAddReservedWord`
* 修改保留词基本数据 `rwUpdateReservedWordBasic`
* 删除保留词 `rwRemoveReservedWord`

### 邀请码管理权限，类别 `7`

* 生成邀请码 `icGenIC`
* 修改邀请码基本数据、状态 `icUpdateICBasic`

### 广告管理权限，类别 `8`

* 修改侧边栏独占展位基本数据 `adUpdateADSide`

### 其他管理权限，类别 `9`

* 设置是否允许发帖 `miscAllowAddArticle`
* 设置是否允许回帖 `miscAllowAddComment`
* 设置是否允许匿名浏览 `miscAllowAnonymousView`
* 设置注册方式 `miscRegisterMethod`
* 设置默认语言 `miscLanguage`

### 菜单权限，类别 `10`

* 管理后台入口 `menuAdmin`
* 后台首页入口 `menuAdminIndex`
* 用户管理入口 `menuAdminUsers`
* 帖子管理入口 `menuAdminArticles`
* 回帖管理入口 `menuAdminComments`
* 领域管理入口 `menuAdminDomains`
* 标签管理入口 `menuAdminTags`
* 保留词管理入口 `menuAdminRWs`
* 邀请码管理入口 `menuAdminIcs`
* 广告管理入口 `menuAdminAD`
* 角色管理入口 `menuAdminRoles`
* 其他管理入口 `menuAdminMisc`

## 数据级权限

#368

### 权限检查流程

1. 如果具有对应业务场景（比如标签-帖子管理）的数据权限，则直接通过
2. 如果没有该数据权限，则认为可以管理所有数据，此时再查是否具有功能级权限

### 数据库

功能级权限相关表：

* 权限表 permission：id, category（显示时分类）
* 角色表 role：id, name
* 角色-权限关联表 role_permission：roleId, permissionId
* 用户-角色关联表 user_role：userId, roleId

数据级权限相关表：

* 数据操作表 data_operation：userId, dataId, bizType

**Comment by luhua** [comment]
1、有了管理权限之后是不是要考虑管理记录，比如某用户的帖子被哪个管理员删除的。
2、帖子管理权限、回帖管理权限是不是可以分领域或者标签来？ 就跟传统的版主或者贴吧吧主一样。

**Comment by 88250** [comment]
@luhua 

1. 需要有管理记录的，这个等后面单独开一个 issue 来做，你可以帮忙提一发记录一下先
2. 按领域、标签分的细节还没有想清楚，目标是应该按照这个信息架构来分权限的，等再想想

**Comment by 88250** [comment]
![qq 20161226132001](https://cloud.githubusercontent.com/assets/873584/21476002/0c713fb2-cb6e-11e6-9405-532a8ba78d28.png)

**Comment by lovecn** [comment]
nice
