### ISSUE TITLE
支付模块、APP 接口

### ISSUE THREAD

**Issue by royburns** [b3log/symphony#342]
1. 支持第三方登录
2. 加入支付模块
3. 一键清空未读消息，或者消息的推送机制修改一下，太多了，我都不敢关注人
4. 提供完整的api，供尝试开发app客户端

**Comment by luhua** [comment]
1. 第三方以前讨论过 #204 ，优先级比较低，目前增加的可能性较低

3.  具体应用场景？ 另外现在支付都需要企业才能申请。

5.  这个确实是，关注目前最新版已经放到首页了。

7. 确实可以考虑的，只是现在没看到有人要开发APP。。。有人开搞的话D应该会支持

**Comment by royburns** [comment]
呃，比如我要兑换积分的话，我就要给D的支付宝转账，然后告诉他我的id，他再给我加积分，其实可以完全接入支付宝或者微信的支付接口哇，这个不需要拍照，而且它们应该都有web支付接口

**Comment by royburns** [comment]
这个应该不需要支付牌照的吧？

**Comment by 88250** [comment]
1. 暂时不增加了，忙不过来哦
2. 具体接口没有研究过，积分充值需求不强烈，暂不考虑吧
3. 有标记已读的，你看下消息列表右边框上有个勾
4. 确实需要考虑，但忙不过来哦..

@royburns @luhua

**Comment by 88250** [comment]
1. 接入第三方登录暂不实现了
2. 支付模块暂不实现了
3. 客户端 API 已经实现 https://github.com/b3log/symphony/issues/416

我先关闭这个 issue 了，欢迎继续讨论。

**Comment by royburns** [comment]
OK，谢谢D大
