### ISSUE TITLE
客户端同步开关

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#343]
目前是开启了同步后，两边的内容会全部同步，昨日发生以下场景：
在黑客派发测试帖，标签SandBox，上solo发现同步了过来。
SandBox标签实际上在HP上不做列表来显示的， 却同步到了solo博客里，个人感觉颇为不合理
同时，为了自由选择需要同步的类型，应该添加标签过滤功能
- 只同步指定标签的
- 不同步指定标签的
以上两者获取其一或都实现，让用户能在solo里写正儿八经的博客文章，能在hp上灌灌水，发表一些讨论

**Comment by 88250** [comment]
其实只需要在发布按钮旁边来个开关吧。。

**Comment by ZephyrJung** [comment]
也是个办法😂
只不过这样不能自动管理了，每次还得注意一下……

**Comment by 88250** [comment]
后面考虑加入这个开关吧。

**Comment by ZephyrJung** [comment]
作为开关的话，没有solo的sym用户是否还得做隐藏？
感觉还是放到设置的B3那里统一管理比较合理

**Comment by 88250** [comment]
开关是否出现就看有没有设置过 B3 key 吧，比设置标签过滤简单且可以随心控制。

**Comment by ZephyrJung** [comment]
![qq 20161117141919](https://cloud.githubusercontent.com/assets/2569600/20378439/1f2fffe6-acd1-11e6-8ce2-61946e7370fc.png)
那在此加个复选框，决定是否同步就好了吧
这个功能可否交给我做？反正这个不着急，你也比较忙，而且感觉我比较需要这个功能

**Comment by 88250** [comment]
来吧。
