### ISSUE TITLE
我想使用这个系统，但是接入百度光广告联盟，需要商业授权吗？

### ISSUE THREAD

**Issue by zhengzhiqiang** [b3log/symphony#347]
你好，我很想拥有自己的一个博客，来记录自己开发过程中的一些 技术点，和大家分享。但是可能想接入下广告联盟，在某个小区域展示下，这样看能否补贴下每个月服务器的费用。这样ok吗？是否需要商业授权？

**Comment by 88250** [comment]
个人使用并且不是以盈利为目的的话可以不需要商业授权。
