### ISSUE TITLE
疯狂的想法 A：多语言实现后端

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#350]
目前 Sym 的后端是 Java 实现的，有个想法是根据业务模块来拆分成多个微服务，每个服务用不同的语言实现，通过 HTTP 通讯，但数据库仍然是 MySQL 同库。

比如：

* 模版引擎涉及前端大量工作，所以依旧是沿用 Java（FreeMarker）
* 数据通过 golang、nodejs、Java、Python、PHP 等实现 

先可以在读请求上尝试。

**Comment by mainlove** [comment]
讲道理 应该修改前端为渲染+其他语言。。。。

**Comment by TiSongWen** [comment]
大D 目前有没有构架的思路呢？

**Comment by 88250** [comment]
@mainlove 那就考虑做客户端了..
@TiSongWen 思路就是拆分

**Comment by TiSongWen** [comment]
大D打算把自己的后台拆分成几个模块呢？

**Comment by 88250** [comment]
@TiSongWen 具体没想好，比如首页可能就是一个。

**Comment by zh-h** [comment]
好可怕，这么大年纪了还这么多精力折腾

**Comment by ZephyrJung** [comment]
@zh-h 你这么说会失去D大的知道么

**Comment by TiSongWen** [comment]
最近开始看微服务相关内容，但还是不清楚应该把一个系统拆分成哪几个微服务。比如 以我们的黑客派为例，主要拆分成哪几个微服务呢？

**Comment by zh-h** [comment]
@TiSongWen 系统不大的话，别接触分拆微服务吧。几个东西配置维护起来很麻烦

**Comment by 88250** [comment]
@TiSongWen 理论上 Service 都可以做成分布式的，不过 @zh-h 说得对

**Comment by andrewlucianlu** [comment]
如果开发多的话，维护就不麻烦了把。而且每个人都可以用自己熟悉的语言，参考维基百科的多语言文章

**Comment by dexvo** [comment]
感觉还是得看未来的规划，为了拆分而拆分属于过度设计。

**Comment by 88250** [comment]
可以预见在不久的将来账号相关部分接口会需要拆分，因为新开的的坑 [代号 Solo.go](https://hacpai.com/article/1505113028471) 将使用社区的账号接口。

**Comment by 88250** [comment]
关闭这个蛋疼的想法，等以后社区人多了再考虑。
