### ISSUE TITLE
疯狂的想法 B：去中心化

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#351]
* 数据通过 P2P 方式在客户端同步，每个客户端都会有完整的数据复制
* 通过本地客户端内置的 HTTP 服务提供访问

**Comment by TiSongWen** [comment]
有几个小困惑。
* 这里的客户端是指 Web端吗？
* 数据是说数据库里的数据吗？

**Comment by 88250** [comment]
* 不是浏览器客户端
* 数据就是数据库里的数据了

**Comment by bigmonkey1803** [comment]
什么数据，这些数据为什么要有完整复制？现在的 “中心”是谁？“黑客派”网？

**Comment by 88250** [comment]
@bigmonkey1803 论坛的全部数据，只是一个构想，类似的产品有 ZeroNet

**Comment by 88250** [comment]
后面单独开项目实现 B3 主链。
