### ISSUE TITLE
搜索文章ID直接进入帖子

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#355]
类似于Blibli的AV号码，通过代码精确打开页面
![default](https://cloud.githubusercontent.com/assets/2569600/21039207/39bbaf16-be17-11e6-8ced-52ad7adf8d25.png)
可在此处搜索代码后直接打开该帖子。代码由想要分享文章的人直接提供
该功能主要是为了装X XD
其实有一点实用功能，比如想在群里分享文章的时候只需要给个代码就行（是我打算写每周艾特的时候想到的）

**Comment by luhua** [comment]
有时间把搜索功能完善吧，现在只能用站外搜索，搜不到准确的内容。。。

**Comment by luhua** [comment]
现在sym上配的ES还不好用，使用algolia又太贵

**Comment by 88250** [comment]
帖子的 id 是时间毫秒，实现的时候可以考虑用个正则匹配一下，如果符合这个搜索条件就直接 query article，然后重定向到该帖。

![qq 20161209140021](https://cloud.githubusercontent.com/assets/873584/21039299/d3279e80-be17-11e6-8904-5b4a0f72084f.jpg)

**Comment by ZephyrJung** [comment]
把时间毫秒用十六进制怎么样，缩短长度，并且是这种形式的一律认为是帖子链接，直接做跳转

**Comment by 88250** [comment]
别人怎么转换。。

**Comment by ZephyrJung** [comment]
good question...:joy:

**Comment by 88250** [comment]
一个好的产品本质上都面临要解决一个问题：bootstrap
这个和“我从哪里来”的哲学命题一样，必须考虑啊。。

**Comment by 88250** [comment]
先从计划里面移除了，因为还没想好 😂

**Comment by 88250** [comment]
我关闭了。
