### ISSUE TITLE
内建角色

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#358]
内建 6 种用户角色，将用于 #259 信任系统，不同角色有不同的功能权限 #337 。

## 0 (Visitor) 

访客，未注册。

* 没有任何权限

## 1 (Default) 

新手，刚完成注册，拥有权限：

* 发帖 `commonAddArticle`
* 更新帖子 `commonUpdateArticle`
* 回帖 `commonAddComment`
* 更新回帖 `commonUpdateComment`
* 感谢帖子 `commonThankArticle`
* 感谢回帖 `commonThankComment`

## 2 (Member) 

普通会员，有过一些交互的注册用户，拥有新手的权限，并附加：

* 点赞帖子 `commonGoodArticle`
* 点踩帖子 `commonBadArticle`
* 点赞回帖 `commonGoodComment`
* 点踩回帖 `commonBadComment`
* 收藏帖子 `commonFollowArticle`
* 艾特用户 `commonAtUser`
* 使用邀请链接 `commonUseIL`

## 3 (Regular) 

资深会员，活跃用户 ，拥有普通会员的权限，并附加：

* 置顶帖子 `commonStickArticle`
* 匿名发帖 `commonAddArticleAnonymous`
* 匿名回帖 `commonAddCommentAnonymous`
* 查看帖子编辑历史 `commonViewArticleHistory`
* 查看回帖编辑历史 `commonViewCommentHistory`
* 艾特参与者 `commonAtParticipants`
* 积分兑换邀请码 `commonExchangeIC`
* 修改标签基本数据、状态 `tagUpdateTagBasic`

## 4 (Leader) 

荣誉会员，帮助管理社区的用户，拥有资深会员的权限，并附加：

* 添加用户 `userAddUser`
* 修改用户基本数据、状态 `userUpdateUserBasic`
* 修改用户邮箱/用户名 `userUpdateUserAdvanced`
* 修改帖子基本数据、状态 `articleUpdateArticleBasic`
* 置顶帖子 `articleStickArticle`
* 取消置顶帖子 `articleCancelStickArticle`
* 重建帖子搜索索引 `articleReindexArticle`
* 修改回帖基本数据、状态 `commentUpdateCommentBasic`
* 给用户充值积分 `userAddPoint`
* 给用户兑换积分 `userExchangePoint`
* 给用户违规扣除积分 `userDeductPoint`
* 生成邀请码 `icGenIC`
* 修改邀请码基本数据、状态 `icUpdateICBasic`
* 添加保留词 `rwAddReservedWord`
* 修改保留词基本数据 `rwUpdateReservedWordBasic`
* 删除保留词 `rwRemoveReservedWord`

## 5 (Admin) 

超级管理员，拥有荣誉会员的权限，并附加：

* 添加帖子 `articleAddArticle`
* 重建所有帖子搜索索引 `articleReindexArticles`
* 删除帖子 `articleRemoveArticle`
* 删除回帖 `commentRemoveComment`
* 添加领域 `domainAddDomain`
* 添加领域标签 `domainAddDomainTag`
* 移除领域标签 `domainRemoveDomainTag`
* 修改领域基本数据、状态 `domainUpdateDomainBasic`
* 删除领域 `domainRemoveDomain`
* 修改侧边栏独占展位基本数据 `adUpdateADSide`
* 设置是否允许发帖 `miscAllowAddArticle`
* 设置是否允许回帖 `miscAllowAddComment`
* 设置是否允许匿名浏览 `miscAllowAnonymousView`
* 设置注册方式 `miscRegisterMethod`
* 设置默认语言 `miscLanguage`

**Comment by zh-h** [comment]
为什么不能吧symphony得项目分模块呢？说不定我能拿权限模块来用

**Comment by 88250** [comment]
@zh-h 多谢啦，已经写好了。说到分模块，我估计会是按语言来： #350
