### ISSUE TITLE
表情彩蛋

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#367]
加入部分热门的自定义表情（包括兔斯基、金馆长、暴走等等），当文字只包含自定义表情对应的描述时，替换为自定义表情
自定义表情有哪些，以及对应的描述等相关信息均不对用户公开
彩蛋，就是要给予惊喜

**Comment by 88250** [comment]
感觉有点好玩，只要不是太影响排版..

**Comment by ZephyrJung** [comment]
所以刚才想到了全替换，也就是说回复中（正文不参与）如果只有表情对应的描述时才替换
反正作为菜单的话，出现可能性应该比较小才行，不吝惜添加替换条件，这样对排版影响就不会很大了

**Comment by ZephyrJung** [comment]
想到了一个更逗得就是表情描述都用某种格式的古文，比如我脑补的“别哭了这次真没救了”的对应描述是：莫哭兮这次真没救了也
23333

**Comment by ZephyrJung** [comment]
额，估计没人能中彩蛋了 :joy:

**Comment by 88250** [comment]
关闭了，谢谢建议！
