### ISSUE TITLE
数据级权限

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#368]
前面考虑了功能级权限 #337 ，比如赋予了某用户帖子管理的权限后该用户就可以管理所有帖子，而实际上我们还需要一些特定业务场景相关的数据级别的权限，比如自定义了一个“Java 版主”角色，这个角色包含的业务逻辑是能够管理：

* Java 标签
* 带了 Java 标签的所有帖子
* 带了 Java 标签的帖子的回帖

使用 ACL 模型实现数据级权限管理，主要解决“某用户是否能够操作某数据”的问题。

**Comment by JPCui** [comment]
都有什么权限？我能想到的只有“删除”（逻辑删除），“恢复”。

> 以前做过贴吧吧主，现在记不得有哪些功能了

我对ACL权限管理的实际业务实现比较感兴趣，所以已经迫不及待了。

**Comment by 88250** [comment]
@JPCui Sym 这套系统的信息架构是自底向上的，通过标签聚合领域，所以存在一个不好解决的问题是：一个标签会属于多个领域，目前想到的就是用 ACL 来实现。

**Comment by 88250** [comment]
暂时不考虑实现了，可在二开时根据实际场景自行实现。
