### ISSUE TITLE
小贴士

### ISSUE THREAD

**Issue by Vanessa219** [b3log/symphony#371]
随机在侧边栏个人信息上面添加一些“隐藏”功能的提示
移动端不添加

**Comment by 88250** [comment]
![qq 20161227163701](https://cloud.githubusercontent.com/assets/873584/21495482/af7a1064-cc52-11e6-9c44-99631133b050.png)

**Comment by ZephyrJung** [comment]
论坛用了很多爱心符号啊
这里我觉得用:pushpin:或者:round_pushpin:或者:memo:比较好吧

**Comment by 88250** [comment]
@ZephyrJung 有道理，稍后调整看看
