### ISSUE TITLE
关注人通知

### ISSUE THREAD

**Issue by Vanessa219** [b3log/symphony#372]
当我关注了你，你是不是应该收到一条消息说我关注了你。

当然可以扣点积分什么的。

**Comment by ZephyrJung** [comment]
这个我觉得没必要
会造成困扰，尤其是像DV这种大触，会被这种没有营养的关注信息烦死吧0.0

**Comment by luhua** [comment]
我觉得关注应该提示。
但现在的提示过多确实影响体验。
建议把关注用户的新帖消息提示取消，放到首页的关注部分，以红点/数字显示，而且这样能让用户更好地分辨tab分类。
