### ISSUE TITLE
未登录访问帖子权限改进

### ISSUE THREAD

**Issue by Vanessa219** [b3log/symphony#373]
背景：我发布了一篇文章，非常想分享出去给大家看，分享出去我也可以得到一定积分（数据已经记录，只是没有具体话罢了）。但是现在问题来了，我分享出去大家看不鸟呀。一下就破坏了我想分享的心情～～～

在全站不登录就不可以看文章的前提下，希望能添加一个功能：

给文章作者添加一个按钮，让文章作者可以切换是否需要登录才能查看此文。
当然觉得不好的话也可以要求管理员处理一下。
再不行，给显示一下这篇文章是否能需要登录才能查看的表示也好呀。

**Comment by ZephyrJung** [comment]
其实我觉得一般的文章应该是免登陆可看，优选登录才能看的

**Comment by luhua** [comment]
嗯，这个可以跟匿名一样，管理员设置角色有这个权限以后，用户发帖时可以选择：
浏览的角色：游客、会员、...
另外，想起一个传统的人气功能==：回复可见

**Comment by luhua** [comment]
今天想到一个思路：
类似于微信朋友圈陌生人十张照片一样，游客每次进入/或者限定时间内，只能浏览十个帖子。之后需要登录才能浏览。

**Comment by fiht** [comment]
@luhua 游客清空一下Cookie就可以继续浏览了～

**Comment by luhua** [comment]
@fiht  对用户来说如果想正常浏览网站，就注册了，就像知乎的首页和其他内容拦截一样，并不是真正的拦截，用户还是可以看的。

**Comment by 88250** [comment]
@luhua 

> 今天想到一个思路：
类似于微信朋友圈陌生人十张照片一样，游客每次进入/或者限定时间内，只能浏览十个帖子。之后需要登录才能浏览。

这个方案不错，我细化一下。在管理员设置了不允许匿名浏览的前提下：

* 有访客（未登录）用户访问帖子时先检查 cookie [visits]（存放帖子 URIs）
   * 如果 visits 达到数量上限则跳转登录
   * 没到达就可以继续访问其他帖子并添加 URI 到 visits 中
* 登录后不检查并清空 visits

**Comment by luhua** [comment]
酷！细节一点点完善了，哈哈。

**Comment by lihuibo128** [comment]
跑了一个solo-2.8.0.war，没有看到所说的可以设置匿名，或者未登陆不能范文帖子的权限，
只有设置访问密码来设置是否有访问的权限，这个跟启动参数的配置有关吗？
我想设置只有登陆才能看到相应的帖子

**Comment by 88250** [comment]
@lihuibo128 这个是 Sym 的功能，Solo 没有匿名发布功能，谢谢。
