### ISSUE TITLE
这种类型的软件采用GPL协议有点太死了

### ISSUE THREAD

**Issue by Sunzhuokai** [b3log/symphony#379]
大多数都有对论坛定制化的需求，采用GPL协议限制有点死，限制了你的目标“做最 NB 的开源社区系统，预计几年以后 82% 的社区都将是 Sym 搭建的”。每个人定制了修改都开源对于这类型的软件也不利。

**Comment by luhua** [comment]
有什么不力呢？

**Comment by 88250** [comment]
有定制需求的话应该走商业授权，谢谢。
