### ISSUE TITLE
“推文” 发帖功能

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#380]
https://hacpai.com/article/1484034455227

**Comment by 88250** [comment]
加入内容的话不大好吧，聚合链接倒是没有问题。

**Comment by luhua** [comment]
@88250  
如果没有内容就是分享链接
有内容的话就是分享+内容聚合

光分享链接感觉体验不是很好，就跟solo一样，你链接过去没有获取内容过来体验好
尤其个人博客网站的分享，有些网站打开很慢或者内容删除了
有时候第三方网站打不开了还可以直接看内容，就行百度快照一样

另一个版权问题，基本上大部分网站都允许保留原文链接转载。
而且推文的功能反而比一般的论坛转载更好，更能体现版权。

从开源方面来考虑，sym也可以作为单独的内容分享聚合系统，做推酷一样的网站。

**Comment by 88250** [comment]
有个难以解决的技术问题，如何抓取内容？

**Comment by luhua** [comment]
@88250  
是有点难，主要还是不同的网站模板是不一样的，所以解决这个问题应该就可以了~ 而内容获取过程中需要匹配的网站模板规则，由用户自己设置，比如使用正则或者path编写。建议使用path，基本上一个网站的内容一行path规则就可以搞定，所有模板规则和网址放到一个文本就可以。

如果没有匹配模板，则不获取内容，用户可手工填写或者留空。留空则不显示阅读模式。

**Comment by 88250** [comment]
还是觉得内容全转有问题，贴链接抓摘要之类倒是可以考虑。

**Comment by 88250** [comment]
社区来个帖子，我们多找一些人讨论一下意义。

**Comment by luhua** [comment]
https://hacpai.com/article/1484034455227

**Comment by 88250** [comment]
暂时不考虑实现了，感谢提议！
