### ISSUE TITLE
关注帖子

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#388]
关注帖子后如果该帖发生以下情况将会发通知给帖子的所有关注者：

* 贴主更新
* 其他人回帖

**Comment by imlu** [comment]
建议运营前期互动不多的情况下可以启动邮件通知~

**Comment by luhua** [comment]
建议运营前期互动较少的情况下可以启用邮件通知~

**Comment by 88250** [comment]
@luhua 邮件推送的话太多了

**Comment by luhua** [comment]
不多，如果有邮件的话，WEB端一种通知就可以，弹窗的默认可以关闭，现在其实WEB端已经有点重复了。。。

类似于github这种机制，邮件+数字提示，其实不错。

**Comment by 88250** [comment]
私信倒是可以考虑开邮件，其他类型的还是不考虑了。

**Comment by luhua** [comment]
嗯，你看看，不过我觉得可以考虑，用户跟管理员不一样，用户回帖后关了网站有时候可能隔几天才上。这种没有太多时间泡论坛，但又愿意互动交流的用户，邮件通知还是很有帮助的。

**Comment by 88250** [comment]
@luhua 后面再看看，先这样吧

**Comment by luhua** [comment]
ok
