### ISSUE TITLE
帖子被设置为优选处理

### ISSUE THREAD

**Issue by Vanessa219** [b3log/symphony#392]
RT：

1. 发送通知给贴主：“XX帖子 已被设置为优选，感谢你对黑客派的贡献 ♥”
2. 奖励贴主 100 积分

**Comment by ZephyrJung** [comment]
挖去，之前的会补上么，我觉得我要发财了

**Comment by ZephyrJung** [comment]
PS……D大的优选评选规则应该改改，老实讲orz
长且原创并不能成为优选的标准
@88250

**Comment by 88250** [comment]
@ZephyrJung 眼目前只能按我个人标准来做，后面会走到社区自治上，按大家的点赞、回帖等等来

**Comment by ZephyrJung** [comment]
搜噶
