### ISSUE TITLE
chrome 输入网址空格可进行搜索

### ISSUE THREAD

**Issue by Vanessa219** [b3log/symphony#395]
如题，不需要用户手动添加，就可以产生效果 https://hacpai.com/article/1485335687213?p=1&m=1#1485491440309

实现方式：

1. 把默认搜索页面地址改为 https://hacpai.com/search?q=%s
2. 使用     <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="HacPai" />

**Comment by 88250** [comment]
http://stackoverflow.com/questions/14196317/what-algorithm-does-google-use-to-make-chrome-browsers-address-bar-to-act-as-a/14496104#14496104
