### ISSUE TITLE
前端增加移入沙箱管理功能

### ISSUE THREAD

**Issue by luhua** [b3log/symphony#446]
## 背景

有些用户会发测试帖 ，或者没有价值的内容，展示在首页和列表会影响网站形象，删除又让用户反感。

## 设计
前端增加**移入沙箱**的功能，类似于点赞、收藏功能，快捷操作。帖子移入沙箱后链接能访问，但不会展示在首页和列表。 功能限于管理角色使用。

## 和 Sandbox 标签区别

Sandbox属于分类测试标签，是发帖前主动填写，主要是测试开发人员用于论坛线上测试、检查功能。
移入沙箱属于管理功能，是对已发的帖进行编辑管理，主要是管理人员用于帖子管理、论坛运维。

**Comment by 88250** [comment]
仔细想了一下，这个功能有点矛盾，管理功能还是封禁或者删除好一些。

**Comment by luhua** [comment]
@88250 不矛盾，删帖和封禁是对违法、广告等贴，封/删掉就不能看了。加入沙箱，帖子还能看，不在列表（或者限时不加入列表），其实是管理人员/编辑对 **上首页、上头条** 进行校对干预而已。

**Comment by 88250** [comment]
那就用沙箱标签吧，因为不会有人和管理员对着干的。

**Comment by luhua** [comment]
@88250 不是这个问题，说白了还是用户体验吧，管理上的细节问题。其实现在的管理都可以用，如果细节打磨下会更好，不过一想，发现工作量也不少。。。

**Comment by 88250** [comment]
不用担心工作量，这样，移动到沙箱这个功能还是走标签，我把操作入口放到前台来，这样跑一段时间看看是否够用。

**Comment by luhua** [comment]
嗯，以后可以考虑下优选、关闭/开启回帖、置顶、删帖、删回帖 这些直接到前台操作。可以给一些角色在前台就赋予内容管理的权限，不用去摸索后台，跳到后台去管理。

**Comment by 88250** [comment]
和 @Vanessa219 讨论了下，这个操作不高频，后面考虑吧

**Comment by 88250** [comment]
暂时不考虑了，谢谢建议！
