### ISSUE TITLE
部署出错

### ISSUE THREAD

**Issue by vvsuperman** [b3log/symphony#448]
用eclipse部署，maven install 然后run on service，抛出异常

java.lang.ExceptionInInitializerError
	at org.b3log.symphony.cache.CommentCache.<clinit>(CommentCache.java:47)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)

代码块：
 static {
        cache.setMaxCount(Symphonys.getInt("cache.commentCnt"));
    }

强行赋值
  cache.setMaxCount(10);
而后再运行

而后报错，
java.lang.ExceptionInInitializerError
	at org.b3log.symphony.repository.TagTagRepository.<clinit>(TagTagRepository.java:45)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
代码见：
private static final int WEIGHT = Symphonys.getInt("tagRelatedWeight");

所以是getInt方法出错了

环境：max os  Tomcat9  jkd8 
如何解决这个问题呢

**Comment by vvsuperman** [comment]
查了下Symphonys类已经被成功的初始化了，而且都是static方法，为啥会报这个错呢

**Comment by 88250** [comment]
我也很费解..从来没有遇到过这个问题 😕

**Comment by 88250** [comment]
用 mvn jetty:run 跑吧

**Comment by vvsuperman** [comment]
问题解决了。。。。。debug了一下，发现是resourcebundle读错文件了，读到test目录下的symphonys.properties，导致值丢失，将test目录下symphonys.properties名称改掉，问题解决 😄

**Comment by 88250** [comment]
哦，好的，我关闭了。
