### ISSUE TITLE
加载静态资源报错

### ISSUE THREAD

**Issue by vvsuperman** [b3log/symphony#449]
启动加载css，js等静态资源报错，无法找到

已经进行了如下配置：
serverScheme=http
serverHost=localhost
serverPort=8080
staticServerScheme=http
staticServerHost=localhost
staticServerPort=8080

而且发布后tomcat webapp目录下都是有静态资源目录的
![image](https://cloud.githubusercontent.com/assets/7919221/25391263/73a16484-2a08-11e7-812a-aebb8e161b05.png)

为何还是加载不到呢

**Comment by 88250** [comment]
F12 看下请求

**Comment by vvsuperman** [comment]
就是访问不到哈
![image](https://cloud.githubusercontent.com/assets/7919221/25410803/88143fde-2a4b-11e7-8f43-fd627bfd063c.png)

**Comment by vvsuperman** [comment]
是不是被拦截器拦截了，静态资源要进行特殊配置么

**Comment by vvsuperman** [comment]
查出来了，是url的问题
不可以：http://localhost:8080/css/base.css?201304262200
可以：http://localhost:8080/symphony/css/base.css?201304262200
这个是在什么地方配置的呢？

**Comment by vvsuperman** [comment]
找到了...
staticPath=/symphony
起了
我先自己玩耍下吧

**Comment by 88250** [comment]
好的，我关闭了。
