### ISSUE TITLE
活动——打字比赛

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#454]
【背景】相信对于程序员而言，如果打字速度不够快，是会遭到鄙视的
（打字慢但是bug率低的大神除外）
我在打码的时候感觉自己速度不如以前快了，觉得每天应当打打代码维持下打字的熟练度，而若单纯的打文章似乎没有什么意义，做项目的话由于需要思考逻辑、调试之类的，也不可能畅快淋漓的敲键盘，于是就有了这个想法：以某些开源代码如算法练习为基础，构建打字的内容，然后形成打字练习。
【设计】作为黑客派论坛活动（总不能都是游戏吧:joy:），寻找单个完整实现的代码，打字界面可以选择。完成后可以看到统计出来的打字速度，和打过这篇代码的排名。

**Comment by 88250** [comment]
等以后想做再开。
