### ISSUE TITLE
用户名变成 _ 的问题

### ISSUE THREAD

**Issue by chenglu** [b3log/symphony#455]
作者辛苦了，我们目前正在构建一个以视频翻译为主的社区网站，我部署了之后，把确认信息发给 /register2 的时候出现了一些小问题，我发现密码等字段没有写入数据库，而 username 变成了 _（下划线）

这里应该把 user 的 status 改为 0（激活状态），密码啊什么都写进去，可是数据库空空如也。

JDK 1.8、Tomcat9、GCE Ubuntu、GCE MySQL

谢谢！

**Comment by chenglu** [comment]
我检查了一下，应该是问题出现在 Cache 上，好像在 Cache 里取 User 的时候，用户名就自动变成那个了，这是不是跟服务器配置等有关？

谢谢！

**Comment by 88250** [comment]
变成`_`的话是说明该用户已经被其他用户“抢占”了，其他同名用户（可能是用户们，可能是邮箱）优先这个用户激活了账号。

**Comment by chenglu** [comment]
没记错的话，这个问题自安装伊始就有了（现在没有开放，就是测试一下先），数据表大致看起来是这样的（username 都是 _，password 都是空，userstatus 是 2），向 register2 发送请求的时候，可以跳转到 guide，但是用户名是 _ ，而且密码没有写入数据库，且签到数据好像也不太正常。

![image](https://cloud.githubusercontent.com/assets/2258420/26248350/e0df0488-3c56-11e7-9661-82a6518c7b96.png)

我输出了请求的数据 json 文件，在 register2 和 addUser 里，数据都正常，最后判断问题可能出在 userCache 上，所以我猜想是不是可能是因为服务器的结构不同，这里也会出现不正常，您认为呢？

我把数据库重置，新注册帐号也是一样的。

感谢百忙之中的解答，很想成为“自豪的使用 symphony”的一员，谢谢！

**Comment by 88250** [comment]
注册那一段的整体流程你没有改过吧？正常流程是：

1. 用户填表单
2. 发邮件
3. 用户从邮件链接过来，选角色设密码
4. 注册成功

**Comment by chenglu** [comment]
没有改动过呐，我观察 register 操作的数据库后台都正常的，相当于在 register2 addUser 的时候，没有把用户数据插入数据库（反倒是在这里把正常的 username 变成了 _）

我今天上午再看看给你答复昂~ 搞了好几天啦，哈哈。

**Comment by 88250** [comment]
好的，先谢谢帮忙了。

**Comment by chenglu** [comment]
我好像还是找不到问题出现在哪里 ;-( 

我在 Mac 上测试了一下（连接远程数据库），好像还是在确认注册（register2）那个页面出问题了，还有哪些可以提示一下的吗？

跟之前的问题一样，还是不能写入密码到数据库，UserStatus 也没有修改，username 却变成了 _

求助~

**Comment by 88250** [comment]
你确定用户名或者邮箱没有重复么？

**Comment by chenglu** [comment]
米有呢，我换过好几个数据库连接的（Google Cloud、阿里云）我现在正在本机的 MySQL 上测试。

会不会这些注册信息被 cache 到服务器了，我瞎说的…

**Comment by chenglu** [comment]
![image](https://cloud.githubusercontent.com/assets/2258420/26281186/f49b6db4-3da4-11e7-9bba-212dfc1d8388.png)

上图是新的数据库注册了新的帐号，结果还是这样（username 是 _ ），下图是因为 password 没有写入到数据库，所以 old password 总是错滴~

![image](https://cloud.githubusercontent.com/assets/2258420/26281197/4e4183a8-3da5-11e7-9cb4-9537162593d1.png)

**Comment by 88250** [comment]
你用的是什么邮件服务？

**Comment by chenglu** [comment]
阿里云邮件，确认信通常会收到两封，困… ;-)

**Comment by chenglu** [comment]
两个 code 是一样的。

**Comment by 88250** [comment]
这个问题好奇怪，因为从来没有其他用户遇到过，我也很纳闷。

**Comment by chenglu** [comment]
我问另外两个问题：

1、目前在后台对用户组的权限做修改的时候提示 500，这个现在属于正常对吧？

2、我的七牛开了是华北区域，.js 文件里我需要修改为 up-z1.qiniu.com，能不能做一个配置？

谢谢！

**Comment by 88250** [comment]
1. 具体是哪个页面，麻烦截个图
2. 七牛好像有个什么限制，具体我不记得了，所以最好还是选华东

**Comment by chenglu** [comment]
好，我换回七牛华东，那个页面的 url 是 /admin/role/adminRole/permissions 如下图：

![image](https://cloud.githubusercontent.com/assets/2258420/26294300/40e6602e-3ef5-11e7-8c2c-01b757b40fc0.png)

![image](https://cloud.githubusercontent.com/assets/2258420/26294315/527a79ec-3ef5-11e7-99c2-9f956624330d.png)

**Comment by 88250** [comment]
谢谢反馈，漏了语言配置。

**Comment by chenglu** [comment]
谢谢 fix bug，我重新开了一台服务器，好像用户名问题不复存在了，睡觉啦，折腾完再联系。

**Comment by chenglu** [comment]
用户名问题导致的原因可能也跟自己修改了语言配置的某些内容有关，没想到这个影响这么大。

额外两个问题：

1、签到数据不记录，一直是 0/0
2、在线写字游戏提交的时候提示 undefined

我特意注册了社区成员做的烘培网站，发现如上两个问题也是存在的。

Thanks!

**Comment by 88250** [comment]
1. 签到的问题我这里重现不了
2. 需要安装 tesseract

**Comment by 88250** [comment]
我先关闭这个 issue 了，如果还有问题请直接跟帖，谢谢。
