### ISSUE TITLE
视频上传与播放

### ISSUE THREAD

**Issue by andyliu2012** [b3log/symphony#457]
支持主流视频格式RM、RMVB、3GP、AVI、MPEG，MP4，WMV，MKV，DAT、ASF，FLV等视频在线播放，以及支持预览（缩略图）等效果，上传文件后名称以实际名称显示（不以时间戳进行展示文件名称）

**Comment by 88250** [comment]
1. 显示的话只能是客户端浏览器支持的（HTML5）
2. 不加时间戳（或者 uuid）的话会重名

**Comment by andyliu2012** [comment]
视频的显示吗？采用浏览器支持的视频格式？

**Comment by 88250** [comment]
使用 `<video>` 标签进行视频播放，这个就看浏览器支持了

**Comment by andyliu2012** [comment]
已经支持了，是吗

**Comment by andyliu2012** [comment]
可以加入第三方开源播放器吗，类似乐视云

**Comment by 88250** [comment]
这个估计得你自己开发了。目前对于媒体类型仅支持嵌入，比如 iframe、object 什么的。

**Comment by andyliu2012** [comment]
在浏览器中的播放可以先实现吗

**Comment by 88250** [comment]
好的，这周末做。

**Comment by 88250** [comment]
播放器：https://github.com/videojs/video.js
