### ISSUE TITLE
找回密码bug

### ISSUE THREAD

**Issue by postdep** [b3log/symphony#467]
当我输入完验证码后按下回车键会提示已发送找回密码邮件，这个时候我再点击确定邮箱里面就有两封邮件

我点一封把密码改了，然后点登出，再重新登录会提示密码错误，然后我到数据库里面看到密码已经被清空

我必须在点另外一封邮件再重新改一次密码才正常

**Comment by 88250** [comment]
谢谢反馈，后面我看下。

**Comment by 88250** [comment]
按照你说的步骤我试了下，没有发现密码会被情况的情况。
