### ISSUE TITLE
抢发TGIF

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#468]
对于特定标签，以TGIF为例，每日限制只有一贴或不允许发，存在即不可再发
再可以发的条件下进行抢发，抢中者根据内容长短进行奖励
特定标签在可以发的条件下，有特别提示（比如首页出现tip）

**Comment by 88250** [comment]
好久没人发 TGIF 了，理想情况下是自发性的发 TGIF 贴，并且标题也是处女座式的统一，可惜理想情况太理想化了。

先关闭 issue 了，好玩的事情以后慢慢做。
