### ISSUE TITLE
代码高亮改进

### ISSUE THREAD

**Issue by Vanessa219** [b3log/symphony#479]
当使用 ```xxx 输入代码片段时，后端 md 解析为 `<pre><code class="language-xxx">` ,
此时如果 xxx 不被解析时，hljs 就无法生效。请解析为 

```<pre><code class="hljs xxx">```

错误事例可参见 https://hacpai.com/article/1503388631671

**Comment by 88250** [comment]
这个是因为原文里面手动指定了。

**Comment by Vanessa219** [comment]
没有修复

**Comment by 88250** [comment]
原文里面手动指定了代码类，所以没法通过程序修正啊。
