### ISSUE TITLE
通过jetty-9.4.6.v20170531 部署时，第一次启动报缺少图片错误，请看看是怎么回事

### ISSUE THREAD

**Issue by yuantianwen** [b3log/symphony#482]
[WARN ]-[2017-08-25 22:29:27]-[org.b3log.latke.repository.AbstractRepository:157]: SQL exception[msg=com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'b3log_symphony.symphony_user' doesn't exist, repository=symphony_user, query=currentPageNum=1, pageSize=2147483647, pageCount=1, sorts=[[key=oId, direction=ASCENDING]], filter=[key=userRole, operator=EQUAL, value=adminRole], projections=[]]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:220]: It's your first time setup Sym, initializes Sym....
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:223]: Database [MYSQL], creating all tables
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_tag, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_referral, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_character, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_liveness, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_notification, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_role, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_emotion, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_link, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_domain, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_permission, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_verifycode, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_vote, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_comment, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_book, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_invitecode, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_follow, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_user_book_article, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_option, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_pointtransfer, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_tag_tag, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_reward, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_role_permission, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_client, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_domain_tag, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_tag_article, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_user, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_user_tag, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_article, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_revision, isSuccess=true]
[INFO ]-[2017-08-25 22:29:27]-[org.b3log.symphony.service.InitMgmtService:227]: Creates table result [tableName=symphony_tag_user_link, isSuccess=true]
[ERROR]-[2017-08-25 22:29:36]-[org.b3log.symphony.service.UserMgmtService:562]: Generates avatar error, using default thumbnail instead
java.io.FileNotFoundException: ./upload/ace27c7f5408459e8713ede7c316a399.jpg (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at org.b3log.symphony.service.UserMgmtService.addUser(UserMgmtService.java:554)

**Comment by 88250** [comment]
把 sym.props 里面的 `upload.dir` 改成绝对路径，然后删除所有表重启（相当于重新初始化一次看看）
