### ISSUE TITLE
你妈逼为啥给我Git上面链接你的sb项目

### ISSUE THREAD

**Issue by lambertwe** [b3log/symphony#485]
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目
你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目你妈逼为啥给我Git上面链接你的sb项目

**Comment by lambertwe** [comment]
请忽略此条消息。我删不掉了。

**Comment by lambertwe** [comment]
评伦删不掉了，请忽略。

**Comment by 88250** [comment]
没事，放轻松 :trollface:
