### ISSUE TITLE
新的帖子类型：问答帖

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#486]
https://hacpai.com/article/1504581779927

## 系分

0. article 加入新的类型 `ARTICLE_TYPE_C_QNA = 5`
1. article 表加入 `articleQnAOfferPoint` 字段作为悬赏积分
2. comment 表加入 `commentQnAOffered` 字段作为采纳标识
3. 积分转账记录类型加入 `ARTICLE_QNA_OFFER`
4. 权限不作调整

**Comment by luhua** [comment]
是不是也可以加一个招聘类型?

**Comment by 88250** [comment]
@luhua 招聘类型不是太通用的场景，暂时不考虑了。
