### ISSUE TITLE
发帖的问题

### ISSUE THREAD

**Issue by gourdbaby** [b3log/symphony#493]
搭建成功以后在发帖的时候无法输入文字，请问如何解决？

**Comment by 88250** [comment]
界面上有报错提示吗？截个图。

**Comment by gourdbaby** [comment]
目前console无报错信息，只是单纯的在发帖页面无法输入文字。

**Comment by 88250** [comment]
界面上应该有提示的，有两种可能：

* 没有上传头像
* 注册时间少于 1 天

你看下界面上面，会有提示的。
