### ISSUE TITLE
慢网速情况下，评论提交过程中的问题

### ISSUE THREAD

**Issue by wangdx** [b3log/symphony#50]
- [x] 1. 在提交（点击提交或Ctrl+Enter）后，按钮变暗（此时貌似是不能点击？）但是还是可以在输入框中输入，并且好像还是可以通过Ctrl+Enter提交，而且提交动作都将被执行，从而造成多次提交；
- [ ] 2. 提交过程是否应该有个progressing bar提示

**Comment by 88250** [comment]
@Vanessa219

**Comment by Vanessa219** [comment]
test

**Comment by Vanessa219** [comment]
progressing bar 还没弄，坐等设计 :haircut:
