### ISSUE TITLE
Account avatar link exists XSS vulnerability too.

### ISSUE THREAD

**Issue by gh0stkey** [b3log/symphony#504]
Hi,man.I hope you can learn by analogy.
You filtered xss vulnerability in user center.But,that's just one place.

There is a xss vul in account avatar link.

I can enter xss payload `"><svg/onload=alert(1)>` at the avatar link.

# My test environment
OS : MacOS 10.12.6
Browser : FireFox
Tool : BurpSuite
Data : 2017.11.18 4:20 PM

# Vulnerability details
Location : /settings/avatar
I setting my avatar,use BurpSuite capture some HTTP Requests packets:
<img width="209" alt="1" src="https://user-images.githubusercontent.com/24655118/32978567-bacda06a-cc7f-11e7-80f7-7f3d89da2afa.png">

## Analysis packets
**First packet info:**
Mthod : POST
URI : /upload
Content : I uploaded the picture content

**Second packet info:**
Mthod : POST
URI : /settings/avatar
Content : JSON Requests -> `{"userAvatarURL":"http://****/upload/76ba68ee6032455483c29df03fa2979e_1.png"}`

When I analyzed the second packet, I knew the process of uploading the avatar.

So,i just need to tested the second packet.I changed the value of the JSON parameter `userAvatarURL` to xss payload `"><svg/onload=alert(1)>`.

<img width="999" alt="2" src="https://user-images.githubusercontent.com/24655118/32978646-72a67ba2-cc81-11e7-9303-b4be766c159d.png">

## Attack 
When person look my avatar, I can get their cookies.
<img width="815" alt="3" src="https://user-images.githubusercontent.com/24655118/32978656-ad77c434-cc81-11e7-90b0-062f676301f3.png">
Come on, my good friend.
Vulnerability Reporter : vulkey(mstsec)

**Comment by 88250** [comment]
Thank you, I fixed it. Other XSS issues like this I think I have fixed. Please tell me if you find something else like this.
