### ISSUE TITLE
为其他用户添加备注

### ISSUE THREAD

**Issue by wenchangping** [b3log/symphony#506]
It is recommended to add notes/memo to other users, just like QQ, or sometimes you can't remember the contrast of characters

**Comment by 88250** [comment]
仔细考虑了一下，这个功能有点鸡肋：

* 如果你很关注他，怎么会不记得他的 id？
* 如果你不关注他，怎么还要备注？

IM 软件需要备注是因为双方是私聊居多，而论坛大部分都是公开讨论交流。
