### ISSUE TITLE
清风明月

### ISSUE THREAD

**Issue by gitors** [b3log/symphony#507]
对于有时候一句话的东西，开个帖子多余，但是不发有心里不痛快，开源中国的那个动弹那种，应该是类似于微博，要搞一个吗？

**Comment by 88250** [comment]
我早有此意 @Vanessa219

**Comment by Vanessa219** [comment]
我觉得不太必要，可以先弄个简版试试水

**Comment by shenjixiang** [comment]
有点像现在的 此刻 这个功能

**Comment by 88250** [comment]
@shenjixiang “此刻”是被动的，其实是当前用户的活动状态。 @gitors 提的这个是微博、随便说说、twitter、知乎的想法、开源中国的动弹，etc...

**Comment by shenjixiang** [comment]
@88250 嗯，这个更偏向用户之间的互动

**Comment by luhua** [comment]
这个功能不错，但没有互动总觉得不够“人性”，发这种内容的出发点本就为了博人眼球，获取点赞（认可）和评论（交流）。

**Comment by gitors** [comment]
![image](https://user-images.githubusercontent.com/31715318/40339272-4df7b278-5dac-11e8-90f8-f119d40a759e.png)
怎么能不随便结交朋友

**Comment by truewangming** [comment]
类似日记本的咩

**Comment by 88250** [comment]
@luhua 先最简化上线，其他的等有了需求再考虑
@truewangming 嗯，是这个本意
