### ISSUE TITLE
Article exists XSS vulnerability

### ISSUE THREAD

**Issue by gh0stkey** [b3log/symphony#509]
Hi,man.We meet again.
Get to the point.This problem appears in the article.

# My test environment
**symphony version : latest**
OS : MacOS 10.12.6
Browser : FireFox
Tool : BurpSuite
Data : 2017.11.23 10:37 PM

# Vulnerability details
Location : /article/**
send private letter to anyone : 
<img width="472" alt="0" src="https://user-images.githubusercontent.com/24655118/33180458-b632789c-d0a7-11e7-87ba-5381886d9aa9.png">
I changed the value of this letter's title to xss payload `'"><svg/onload=alert(1)>` and then send it.

You must send two private letters.This will trigger vulnerability.
Open one of the letters `/article/**` : 

<img width="877" alt="1" src="https://user-images.githubusercontent.com/24655118/33181531-866c7b36-d0ab-11e7-9c1d-fafa5910dc09.png">

# Attack

When person open the link, I can get their cookies.

HTML code :
`<link rel="prev" title=""><svg/onload=alert(1)>" href="http://www.**.com/article/1511283398881">`
`<a rel="prev" class="tooltipped tooltipped-w" aria-label="上一贴: "><svg/onload=alert(1)>"`
 Vulnerability Reporter : vulkey(mstsec)

**Comment by 88250** [comment]
Thank you ag, We will fix it asap.
