### ISSUE TITLE
消息提示已读问题

### ISSUE THREAD

**Issue by ZephyrJung** [b3log/symphony#510]
目前逻辑是，要么在悬浮窗口点对号取消提示，要么点进消息页面，再点对号取消提示
关于后者感觉体验不好，点进消息页面时实际已经阅读，却还需要再点一下才能取消提醒

**Comment by 88250** [comment]
进入通知涉及的页面会自动标记已读的，如果没有标记，说明是网络问题，我关闭了，谢谢反馈。
