### ISSUE TITLE
在本地环境测试，进行注册的时候，抛出异常，偶尔出现

### ISSUE THREAD

**Issue by yangzhengnan** [b3log/symphony#515]
注册失败 - org.b3log.latke.repository.jdbc.JDBCRepositoryException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'userAvatarURL' at row 1

**Comment by 88250** [comment]
改过 sym.props 中的 upload.dir 么？

**Comment by yangzhengnan** [comment]
没有，配置如下：upload.img.maxSize=1048576
upload.file.maxSize=104857600
upload.dir=./upload/

**Comment by 88250** [comment]
发一个目前有头像的图片地址看下。

**Comment by 88250** [comment]
已经尝试修复，你拉最新代码试试。
