### ISSUE TITLE
建议 标签管理 图片路径提供上传功能及选取系统内已有图片功能（tags文件夹下）

### ISSUE THREAD

**Issue by ronger-x** [b3log/symphony#517]
建议 标签管理 图片路径提供上传功能及选取系统内已有图片功能（tags文件夹下）

**Comment by 88250** [comment]
我想选择功能就不提供了，上传功能倒是需要来一发，提高标签整理效率。

**Comment by ronger-x** [comment]
选取功能是方便新搭建的sym使用系统内已存在图标进行标签维护，系统只是默认创建了sym和blog3标签，主流的软件或者框架系统提供了图标但是不方便选取维护

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: D <notifications@github.com>
发送时间: Monday, December 11, 2017 10:28:40 AM
收件人: b3log/symphony
抄送: ronger; Author
主题: Re: [b3log/symphony] 建议 标签管理 图片路径提供上传功能及选取系统内已有图片功能（tags文件夹下） (#517)


我想选择功能就不提供了，上传功能倒是需要来一发，提高标签整理效率。

―

**Comment by 88250** [comment]
自带的那些图标已经很久没有添加新的了，其实也是为了使用外链。不然自己整理图标很麻烦的，需要裁剪大小之类的。还是用上传外链比较简单，裁剪也可以走七牛的图片样式。

**Comment by 88250** [comment]
暂时不考虑实现了，谢谢建议！
