### ISSUE TITLE
用户综合排名

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#534]
### 计算方式

注册时间天数 + 邀请注册数 * 100 + 积分余额 + 昨日活跃度 * 10 + 帖子分享点击计数 + 发帖数 * 200 + 回帖数 * 10 = 排名点数

例如：1825 + 1620 * 100 + 230000 + 300 * 10 + 7000 + 500 * 200 + 7000 * 10 = 573825

### 技术实现

跑定时任务计算昨日用户排名，结果写 user 表 userGeneralRank 字段。

----

目前暂时仅在商业版中进行实现。

**Comment by ZephyrJung** [comment]
没有代码贡献量加成么 :joy:

**Comment by 88250** [comment]
@ZephyrJung 在我心中已经有了
