### ISSUE TITLE
违规文章处理

### ISSUE THREAD

**Issue by yangzhengnan** [b3log/symphony#536]
建议，对违规文章的处理是：
最好是有个操作，设置完后，就发布者自己能看，是正常的，别人都看不到，列表上也不显示。
比如博客园cnblog，被管理员判定低质量文章后，除非直接敲入该文章的网址可以直接看，否则从网站的任何一个地方是没有入口可以看到的

**Comment by 88250** [comment]
目前移入沙箱后在外面暴露的地方麻烦列一下。

**Comment by yangzhengnan** [comment]
目前，在近期热议可以看到

**Comment by 88250** [comment]
“移入沙箱”的操作目前是设置标签为 `Sandbox`，设置后就不会在列表里出现了。
