### ISSUE TITLE
周邮件推送帖可后台设置

### ISSUE THREAD

**Issue by yangzhengnan** [b3log/symphony#537]
每周推荐优化
思路一：这个每周推荐，除了算法自动生成外，是否可以人工干预，比如每周推荐10条，优先推荐人工的，剩余的算法补充
思路二：每周推荐之前，推荐的内容，能否先让系统管理员看看，要不然完全就是黑盒子，管理员看了之后，感觉不好的可以手动修改

**Comment by 88250** [comment]
这个估计要自己改代码实现了，目前我觉得自动算法还是不错的。

**Comment by sides8** [comment]
我比较赞成思路二的做法

**Comment by 88250** [comment]
v3.1.0 加入该特性，在帖子管理中可对帖子设置推荐标识，优先进行推荐。
