### ISSUE TITLE
邀请链接改进

### ISSUE THREAD

**Issue by ldan2012** [b3log/symphony#547]
1.建议点进邀请链接的时候把那个后缀加到sessionStorage；
 我推荐了好多人，别人都是进去后直接进首页了，然后自带的那个后缀就没了   。
2.建议hacpai所有链接后面都能追加推荐人参数

**Comment by Vanessa219** [comment]
@ldan2012 2.5.0 分支已修复

**Comment by 88250** [comment]
黑客派已部署。
