### ISSUE TITLE
修改帖子时遇到的两个 BUG

### ISSUE THREAD

**Issue by LyZane** [b3log/symphony#548]
编辑一个两年前的帖子
编辑完后发现提交按钮为灰色，不明所以。

然后在页面顶部发现一个小小的提示，需要设置头像后才能发帖。

我一直都是有头像的，这是第一个 bug。

然后呢，我写半天，也不知道有没有离线保存，当然不肯跳转到其他页面去。
就算在新窗口修改好头像之后回来帖子的编辑页，也需要刷新页面，总之是担心编辑的内容搞丢。

所以打开了浏览器的开发人员工具，去掉了按钮的禁用状态，然后点了一下，发现可以了。
服务器端没有做检查，这是第二个 bug。

---

另外，提交按钮边上那个 “同步” 选项，我估计得有一半以上的人不知道是干嘛用的。

**Comment by 88250** [comment]
好的，谢谢反馈，后面修复。
