### ISSUE TITLE
沙箱机制建议

### ISSUE THREAD

**Issue by tom798** [b3log/symphony#585]
这个sandbox作为标签属性感觉更灵活一点

**Comment by 88250** [comment]
现在是标签，你的意思是改成什么呢？

**Comment by 88250** [comment]
那和现在用 Sandbox 作为标签有啥区别？

**Comment by tom798** [comment]
如果有人需要多个不同类型的沙箱，配置一下标签属性就可以了

**Comment by 88250** [comment]
沙箱之前的设计只有一个作用，就是不在列表展示该帖子，配置“不同类”的沙箱“我还是没理解你的场景。

**Comment by 88250** [comment]
先关闭了，如有需要再打开讨论。
