### ISSUE TITLE
为何要重写spring 的功能呢？

### ISSUE THREAD

**Issue by ldlqdsdcn** [b3log/symphony#586]
请问为何要重写spring 的Service，有必要吗？
repository 是持久层？
processor 是controller层？
别人不能很快了解你的设计，也很难参与到你的项目里来啊。

**Comment by tom798** [comment]
说的好像有几分道理呢

**Comment by 88250** [comment]
请看 [为什么又要造一个叫 Latke 的轮子](https://hacpai.com/article/1403847528022?r=88250)

**Comment by ldlqdsdcn** [comment]
牛啊，你是想前颠覆整个java 规范。

**Comment by ldlqdsdcn** [comment]
我个人觉得，有很多弱类型语言 跟你思想一样。你这样用，是用java写弱类型语言的代码。

**Comment by ldlqdsdcn** [comment]
不过架构非常有效，看着非常清爽，大师级！！！

**Comment by 88250** [comment]
就是实现自己的一些想法而已，凑合能用而已。

![qohlil7 hxqc3 lcr1 5n 0](https://user-images.githubusercontent.com/873584/37236861-43cfb6fe-2447-11e8-9cd6-a22523d18974.jpg)
