### ISSUE TITLE
社区页面样式 能不能搞的创新好看点。。。。。。。。

### ISSUE THREAD

**Issue by mainlove** [b3log/symphony#59]
现在这样普通了点， 新用户看一眼就觉得普通

扁平化啊扁平化

**Comment by 88250** [comment]
最近加入了一些动态元素：

* @、表情的自动完成
* 评论自动推送，趋向于聊天场景
* 帖子列表动态效果，用户进入/离开/评论帖子
* 讨论组，隐私保护
* 图片剪切板上传

应该会比较好玩，这个 issue 我先关闭了。
