### ISSUE TITLE
文章上首页

### ISSUE THREAD

**Issue by tom798** [b3log/symphony#590]
能否首页里面的这个最新，需要编辑推荐的，才显示在首页，不是所有的最新文章都上首页！如果增加这个流程复杂的话，最起码有个算法过滤，比如阅读达到多少或者点赞数减去踩脚数，这样的一个考量。

**Comment by 88250** [comment]
已经实现了 Reddit 热帖排序算法，用 ArticleQueryService#makeRecentGoodQuery 这个捞出来的就是了。

Sym 主要是侧重于 UGC，PGC 的管理不打算做太强，因为可以通过人为运营操作实现，比如通过多个小编账号来发文，管理员后台可以指定发文时用的用户名。
