### ISSUE TITLE
领域可设置是否渲染导航

### ISSUE THREAD

**Issue by onebe** [b3log/symphony#596]
建议领域的名称、url等允许进行修改，后期也可以针对性的进行seo优化。
目前名称只允许大小写修改，url无法修改。

另外再增加一个选项，该领域是否显示在主菜单，如果否，则不显示在主菜单里面。

**Comment by 88250** [comment]
领域名称只能允许大小写修改，URL 可以随意改。如果要改名称就重新建一个，删了老的。关于是否显示在导航上这个需求后面实现，谢谢提议！

**Comment by luhua** [comment]
建议设置导航不显示时，/domains 中仍可以显示，封禁后所有都不显示。

**Comment by 88250** [comment]
@luhua OK 了，多谢提醒我都忘了还有这样一个页面 😅 。另外，封禁暂时不管了。
