### ISSUE TITLE
标签管理建议增加标签是否需要审核功能

### ISSUE THREAD

**Issue by onebe** [b3log/symphony#597]
目前标签允许用户随意创建，建议增加后台管理功能，
1、审核标签，只有审核通过的标签，才允许给其它用户使用；
2、是否需要审核标签，可以有个开关；
3、标签允许管理员进行推荐首页显示；

**Comment by 88250** [comment]
Sym 的信息架构是自底而上的，从标签聚合领域。结构上标签是扁平化的，不分层级，可通过帖子进行关联。标签允许用户随意创建、使用，这一点就是为了让流行的标签逐渐浮出呈现，让用户发帖时免去选择，对用户来说更简单更自由。
