### ISSUE TITLE
文章列表显示优化

### ISSUE THREAD

**Issue by onebe** [b3log/symphony#598]
1、文章列表，如果发布视频能否像发图片一样，也显示一个预览视频图在右边显示，点击视频图片可以进入帖子内容。
2、文章列表显示，如：作者头像太大，有点抢眼；除了阅读数，还可以增加下手机版中帖子的诸多指数，比如回复数等。可参考下简书（https://www.jianshu.com/） 或者知乎。

**Comment by Vanessa219** [comment]
第一条需要 @88250 抽取视频图片放到摘要图中即可。
第二条中的回复数在列表中表现为回帖数

**Comment by 88250** [comment]
暂时不做了，感觉必要性不大。
