### ISSUE TITLE
请问如何去除邮箱注册

### ISSUE THREAD

**Issue by flyyuan** [b3log/symphony#616]
想去掉邮箱注册，直接用账号密码就够了

**Comment by 88250** [comment]
修改注册、创建用户相关代码。你可以参考一下管理员后台创建用户的实现。

**Comment by karott** [comment]
@88250 你好，有改好的仅仅用户密码注册的代码么

**Comment by 88250** [comment]
> @88250 你好，有改好的仅仅用户密码注册的代码么

没有，麻烦自行修改。
