### ISSUE TITLE
七牛云存储区域与上传域名配置

### ISSUE THREAD

**Issue by dennykong** [b3log/symphony#617]
七牛非华东区 bucket，上传报400：incorrect region, please use xxxx.qiniu.com。因为 js 里固定了上传域名  https://up.qbox.me。

建议设置动态配置

存储区域 | 地域简称 | 上传域名
-- | -- | --
华东 | z0 | 服务器端上传：http(s)://up.qiniup.com客户端上传： http(s)://upload.qiniup.com
华北 | z1 | 服务器端上传：http(s)://up-z1.qiniup.com客户端上传：http(s)://upload-z1.qiniup.com
华南 | z2 | 服务器端上传：http(s)://up-z2.qiniup.com客户端上传：http(s)://upload-z2.qiniup.com
北美 | na0 | 服务器端上传：http(s)://up-na0.qiniup.com客户端上传：http(s)://upload-na0.qiniup.com
东南亚 | as0 | 服务器端上传：http(s)://up-as0.qiniup.com客户端上传：http(s)://upload-as0.qiniup.com

**Comment by 88250** [comment]
谢谢反馈，后面会通过配置项进行区域和域名配置。
