### ISSUE TITLE
Log打印问题

### ISSUE THREAD

**Issue by liangyuanpeng** [b3log/symphony#648]
``
LoginProcessor#forgetPwd
``

在捕获异常中打印日志的语句有问题，没有写上name变量

``
LOGGER.log(Level.ERROR, msg + "[name={0}, email={1}]", email);
``

**Comment by liangyuanpeng** [comment]
VerifycodeProcessor的LOGGER变量没有使用到，属于无用代码，建议删除

**Comment by liangyuanpeng** [comment]
VOteProcessor的LOGGER也是一样没有使用到，这种没有使用的变量建议都删除

**Comment by 88250** [comment]
好的，谢谢反馈。
