### ISSUE TITLE
Windows 10 Edge 浏览器回复框无法输入

### ISSUE THREAD

**Issue by zh-h** [b3log/symphony#657]
```
2 SCRIPT5022: SyntaxError
article.d7e546da0cca9cf28aaa.js (1,31817)

 SCRIPT5007: Unable to get property 'focus' of undefined or null reference
article.d7e546da0cca9cf28aaa.js (1,261439)
```
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134

![edge-bug](https://user-images.githubusercontent.com/13273151/41473979-63059abe-70ed-11e8-9871-feef7070d42a.png)

**Comment by zh-h** [comment]
@Vanessa219 我正在本地启动开发模式检查

**Comment by zh-h** [comment]
![image](https://user-images.githubusercontent.com/13273151/42037220-6b1cff3a-7b1a-11e8-825f-1ddf6accc22b.png)
hacpai.com 删库啦？

**Comment by 88250** [comment]
😅 已经恢复。

**Comment by Vanessa219** [comment]
@zh-h 已修复。IE 目前暂不支持 ws
