### ISSUE TITLE
DomainCache 可能引发并发的问题

### ISSUE THREAD

**Issue by liangyuanpeng** [b3log/symphony#658]
在``DomainCache#loadDomains``这个方法中使用了
```
DOMAINS.clear();
```
这样的一行代码，在并发的情况下执行了这一行代码，而另一个请求执行了```getDomains```这个方法时

```
if (DOMAINS.isEmpty()) {
            return Collections.emptyList();
        }
```

这里判断就会返回一个空的集合，目前没有发生过类似的情况吗？

还是说会有其他地方进行一个数据完整性的操作以至于 不会发生这样的情况

**Comment by 88250** [comment]
谢谢反馈，稍后加个锁简单处理一下。

**Comment by liangyuanpeng** [comment]
不用锁的，更好的方式是new一个新的临时集合

```
        DOMAINS.clear();
        List<JSONObject> DOMAINS_TMP = new ArrayList<>();
        DOMAINS_TMP.addAll(domainQueryService.getMostTagNaviDomains(Integer.MAX_VALUE));
        DOMAINS = DOMAINS_TMP;
```

直接改变对象的引用就可以了，当然了，``DOMAINS``变量需要取消final修饰符

**Comment by 88250** [comment]
赋值的时候 isEmpty 也会被执行的嘛。

**Comment by liangyuanpeng** [comment]
会执行，但是会返回一个空的集合，应该是上面域的那一行吧

**Comment by 88250** [comment]
返回空集合岂不是没达到需要的效果么？

**Comment by liangyuanpeng** [comment]
才明白，你是在说DOMAINS = DOMAINS_TMP;这一步骤是吗

赋值过程是不会有执行isEmpty 的时候的，

要么是使用前一个对象地址，也就是正在使用的DOMAINS 内存数据

要么是使用赋值后的对应地址 也就是新的DOMAINS_TMP

因为赋值没有get  set这样的一个过程，是直接改变内存地址

**Comment by 88250** [comment]
是的，所以还是有可能是空的。

**Comment by liangyuanpeng** [comment]
不会有空的时候呀，

要么是使用原有内存中的数据，也就是```DOMAINS``` 这个集合中的数据

要么是完成赋值操作以后使用 ```DOMAINS_TMP```这个集合中的数据，赋值完成后```DOMAINS_TMP```集合已经完成了数据的刷新，是有数据的

**Comment by 88250** [comment]
一个线程执行了 clear , 另一个执行 isEmpty 返回 0，这不就空了么。比如 load 数据需要很长时间，这是时间段内都是空的嘛。如果不是这样的话，实现 copy on write 也都可以不用加锁了。

**Comment by 88250** [comment]
赋值更新引用时也有可能空的，除非用 CAS 原语。

**Comment by liangyuanpeng** [comment]
这是我之前的一个高并发实战经验，分享给你，直接赋值就能解决


锁没什么必要加我认为，影响性能，量大的时候就卡了，量少不影响功能使用


不管怎样，问题解决就好

**Comment by 88250** [comment]
谢谢分享。PS 读写锁性能还是可以的。
