### ISSUE TITLE
首页下发很多无用数据

### ISSUE THREAD

**Issue by liangyuanpeng** [b3log/symphony#661]
例如：

- 发帖失败的提示，可以在发帖提交后判断进行下发
- 邀请码相关数据
- 登陆 或者 修改密码等相关提示，都可以在进行相应动作后判断
- daysAgoLabel 等不经常修改的数据，可前端写死
- "invalidDomainTitleLabel":"领域标题不能为空" 

很多都可以在进行相应操作的时候需要提示语才下发提示语，将流量后置

不太明白目前这样将所有数据一次性下发是为了什么，个人认为很浪费流量，到达宽带上限的时候还会导致页面卡，慢，导致用户体验

只看了看首页的数据下发情况，其他页面没有查看

**Comment by 88250** [comment]
这些文案是 js 里面用的，前端校验时使用，而且得支持多语言，所以只能这样实现了，暂时没找到更好的方案 😓

**Comment by liangyuanpeng** [comment]
为什么不能发请求时才下发具体的文案

**Comment by 88250** [comment]
前端校验（请求前）就要用了。

**Comment by liangyuanpeng** [comment]
对于这种，如果不是经常变化的话，前端写死就好吧

**Comment by 88250** [comment]
要处理多语言，没法写死。

**Comment by liangyuanpeng** [comment]
那这个始终要下发，没办法

但还有优化点就是，到特定页面才下发特定的文案，

现在进入首页就下发其他页面操作才会用到的文案

**Comment by 88250** [comment]
开发引入模版工作量就大了，这个权衡过了，不会占多少流量的。
