### ISSUE TITLE
为什么不完善Elasticsearch呢？

### ISSUE THREAD

**Issue by WhiteML** [b3log/symphony#668]
1. 看你早先的帖子说要自己实现SearchQueryService

1. 但是最近发现你已经实现了

1. 但是有个bug,导致搜索不出来

>对SearchQueryService   84行进行修改

` 
  queryString.put("fields", new String[]{Article.ARTICLE_TITLE, Article.ARTICLE_CONTENT});`

>修改后

 `private static final String SUFFIX = ".keyword";
 queryString.put("fields", new String[]{Article.ARTICLE_TITLE+SUFFIX, Article.ARTICLE_CONTENT+SUFFIX});
` 

像大D这样的大牛，肯定知道，但为啥不完善了呢？

**Comment by 88250** [comment]
帮忙 PR 吧。
