### ISSUE TITLE
如果关闭注册的邮件验证...？

### ISSUE THREAD

**Issue by mojie126** [b3log/symphony#669]
RT~~

**Comment by 88250** [comment]
社区版不支持其他注册方式，如果你要实现的话可以参考一下管理后台添加用户那部分代码。

**Comment by mojie126** [comment]
不是要其他注册方式，是不想用邮件验证，内网没邮件可以发...

**Comment by 88250** [comment]
内网的话直接后台添加账号吧，或者对接一下你们的内部系统。
