### ISSUE TITLE
3.1.0点击admin管理页报500错误

### ISSUE THREAD

**Issue by mojie126** [b3log/symphony#685]
JDK 1.8.162
TOMCAT 9.0.10

**Comment by 88250** [comment]
新安装的话不能重现你说的问题。如果你是从老版本升级的话对比 repository.json 改数据库，并对比代码手动更新权限相关表。

**Comment by mojie126** [comment]
竟然连个平滑升级的方法都没有...？

**Comment by 88250** [comment]
目前没有，我也是手动改表结构升级的。
