### ISSUE TITLE
链接榜单

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#686]
* 之前的链接熔炉是主动提交链接然后按链接得分排序展现，现去掉主动提交，改为按帖子/回帖内容中的链接点击计数排序展现
* 访问路径 /top/link

**Comment by gitors** [comment]
时不时的来看看动态，证明我在关注。。。
熔炉，我觉得可以拿到链接内容，然后，在用户 在hacpai 搜索的时候，根据内容关键字，将其加到搜索结果，这样，如果用户搜索的内容hacpai 没有 对应结果，也能做到 推荐 相关内容给他。给了用户一个 获取自己所需内容新途径。。不知可行否？

**Comment by 88250** [comment]
这个“相关”实现起来很难啊（不只有内容索引，还要考虑内容更新），目前站内的搜索还有待提升，站外的暂时就不考虑了。

多谢思路，等以后有机会了我找个场景试试看。

**Comment by gitors** [comment]
其实我也觉得这个实现起来应该是比较难的，我以为我这样觉得是因为我菜。。。

**Comment by 88250** [comment]
你的感觉是对的，因为我也菜。。。。

**Comment by gitors** [comment]
大佬不要谦虚
