### ISSUE TITLE
properties支持环境变量

### ISSUE THREAD

**Issue by zhaochaobo** [b3log/symphony#695]
properties配置中能否提供对环境变量的支持，便于容器化

**Comment by 88250** [comment]
目前没有支持，配置项有点多，考虑挂卷吧。

**Comment by 88250** [comment]
Lakte 从 v2.4.8 起支持环境变量加载，具体请看：

* https://github.com/b3log/latke/issues/93
* https://github.com/b3log/latke/issues/94
