### ISSUE TITLE
jQuery.Deferred exception: undefined is not an object (evaluating 'data.files[0].type.split')

### ISSUE THREAD

**Issue by tuyuan2012** [b3log/symphony#709]
你好，Mac系统下，用Safari浏览器编辑个人图片个人头像，上传中文目录下的图片失败，非中文目录没有问题，用Chrome浏览器上传任何目录下的图片都正常！Safari浏览器报错日志：jQuery.Deferred exception: undefined is not an object (evaluating 'data.files[0].type.split')
![snip20180805_2](https://user-images.githubusercontent.com/3121889/43686837-7b9d8cce-98fe-11e8-9e27-dd871818669d.png)

**Comment by Vanessa219** [comment]
请问你使用的是那一个版本？或者有演示地址么？
本地最新代码无法重现

**Comment by tuyuan2012** [comment]
3.1.0、3.2.0版本都有这个问题

**Comment by Vanessa219** [comment]
我在 safari 下上传图片【未命名.png】 没有错误提示。版本号：版本 11.1.2 (13605.3.8)

**Comment by tuyuan2012** [comment]
你好，不是中文名称的图片，是中文目录下的图片素材【/Volumes/HD/项目素材/logo-ai.png】 。Safari版本号：11.1.1(13605.2.8)

**Comment by Vanessa219** [comment]
上传组建用了 https://github.com/blueimp/jQuery-File-Upload，看了一下他的 Demo 也不支持 https://blueimp.github.io/jQuery-File-Upload/ 。不知道他后续是否能支持？

**Comment by 88250** [comment]
我先关闭了，第三方库的 issue 估计一时半会也没法搞定。

**Comment by tuyuan2012** [comment]
你好，你们官网论坛https://hacpai.com/settings/avatar 个头像片上传用的什么库呢？这边用Safari上传中文目录下的图片是没有问题的！如果jQuery-File-Upload三方库没有修复该issue，能将用户图片编辑改用你们官网论坛采用的库么？
![image](https://user-images.githubusercontent.com/3121889/43874917-f9546a88-9bc0-11e8-87ab-accf33d1d2c4.png)

**Comment by 88250** [comment]
Sym 商业版没有用第三方上传库，社区版因为时间精力有限，暂时没有修改的计划，请谅解一下，谢谢支持！

**Comment by tuyuan2012** [comment]
好的，那我们自己想办法解决，谢谢，希望越来越好～
