### ISSUE TITLE
商业版和社区版latex公式渲染问题

### ISSUE THREAD

**Issue by cbamls** [b3log/symphony#717]
$$ IDCG\_p = \sum_{i=1}^{|REL|}  \frac{2^{rel_i} -1}{log_2 (i+1)} $$
在社区版 渲染失败

**Comment by 88250** [comment]
启用 marked 引擎试试。

**Comment by cbamls** [comment]
symphony也要服务器安装node 启动marked 来解析markdown么 ？？node js/marked/http.js

**Comment by 88250** [comment]
是的。

**Comment by cbamls** [comment]
成功了 非常感谢 D哥～
