### ISSUE TITLE
对于清风明月的一点建议

### ISSUE THREAD

**Issue by gitors** [b3log/symphony#720]
使用了一段时间，发现问题如下：
如果 对方发的文字过多，首页显示的时候是显示部分的，如果需要查看，就要点进主页去查看，个人觉得稍有不便。
期望情况：鼠标悬浮的时候，以卡片的形式显示 全文、作者简要 等。

**Comment by 88250** [comment]
有图片或者链接的怎么处理呢？显示 [链接] [图片] 么？ @Vanessa219 来一起讨论讨论。

**Comment by gitors** [comment]
原来这东西可以发图片的啊。。。

**Comment by gitors** [comment]
![image](https://user-images.githubusercontent.com/31715318/44016897-32f3d454-9f09-11e8-829e-96bbaa8d97a6.png)
这种形式怎么样？

**Comment by 88250** [comment]
我觉得可以考虑实现一下。

**Comment by Vanessa219** [comment]
侧边栏只是一个概览。可以在输入框上加一个  https://hacpai.com/watch/breezemoons 的链接。然后侧边栏点击后进行锚点定位如何？

**Comment by gitors** [comment]
@Vanessa219  并没有理解你的意思

**Comment by 88250** [comment]
所以结论是....暂时不做修改？

**Comment by 88250** [comment]
和 V 讨论了下，暂时不调整了，感谢反馈！
