### ISSUE TITLE
Symphony项目结合Nginx能做负载均衡么？

### ISSUE THREAD

**Issue by tuyuan2012** [b3log/symphony#742]
你好，Symphony项目结合Nginx能做负载均衡么？为什么serverHost为什么需要在工程里配置呢？不能通过上下文直接获取么？
谢谢！

**Comment by 88250** [comment]
1. 社区版不支持集群，多进程负载均衡会有问题
2. Servlet 里面没有获取域名的方法，上下文路径可以获取
