### ISSUE TITLE
社区版的几个问题

### ISSUE THREAD

**Issue by zxh2013** [b3log/symphony#743]
在使用社区版时，有以下几个问题：
1、用户签到时如有特殊字符，则出现tomcat级别错误。
    解决方案：checkin.ftl模板里的签到接口请求地址进行encodeURI编码
2、用户上传头像时提示地址up.qbox.me不可用
   解决方案：根据提示，把相应地址修改为up-z1.qiniup.com

**Comment by 88250** [comment]
1. 签到时候为什么会有编码问题，这个麻烦详细指出一下，谢谢
2. 确实有这个问题，参考 https://github.com/b3log/symphony/issues/617

**Comment by zxh2013** [comment]
签到时确实是有的，我遇到的是参数geetest_seccode里面还有一个"|"特殊字符，导致tomcat级别异常。
checkin.ftl第54、55、56行。
var result = captchaObj.getValidate();
                    window.location.href = "${servePath}/activity/daily-checkin?geetest_challenge=" + result.geetest_challenge +
                            "&geetest_validate=" + result.geetest_validate + "&geetest_seccode=" + result.geetest_seccode;

修改后：
var result = captchaObj.getValidate();
                    window.location.href = "${servePath}/activity/daily-checkin?geetest_challenge=" + encodeURI(result.geetest_challenge) +
                            "&geetest_validate=" + encodeURI(result.geetest_validate) + "&geetest_seccode=" + encodeURI(result.geetest_seccode);

**Comment by 88250** [comment]
收到，谢谢。
