### ISSUE TITLE
开源版本在windows中文版的chrome 69中，网站中用到一些js文件(有非ASCII字符的utf8编码的js文件）导致乱码（把utf8编码的js文件按GBK加载导致）

### ISSUE THREAD

**Issue by zoowii** [b3log/symphony#762]
**Describe the bug 描述问题**
开源版本在windows中文版的chrome 69中，网站中用到一些js文件(有非ASCII字符的utf8编码的js文件）导致乱码（把utf8编码的js文件按GBK加载导致），比如编辑框的cursor的光标显示为乱码

**To Reproduce 重现步骤**
Steps to reproduce the behavior: 请描述如何重现这个问题：
1. windows 10中文版下部署开源版本master分支
2. 打包后用apache tomcat 9启动
3. 用chrome 69访问默认生成的文章页面
4. 点击回帖按钮，查看编辑框，发现编辑框的cursor的光标显示为乱码

**Desktop (please complete the following information): PC 端环境**
 - OS: windows 10中文版
 - Browser chrome 69
 - Version master分支

**Additional context 其他信息**
已发现是因为一些js文件中用到非ASCII的utf8字符而不是使用unicode字符，我用工具https://github.com/zoowii/js2unicode 把webapp目录下的js文件中的非ASCII编码的字符转出unicode字符后问题就没有了。稍候提交一个修复的PR

**Comment by 88250** [comment]
会在 https://github.com/b3log/symphony/issues/765 中修复，谢谢反馈。

**Comment by heilaoda** [comment]
这个问题我用最新的master分支代码发现还是存在的

**Comment by 88250** [comment]
@heilaoda 还是编辑器乱码么？

**Comment by heilaoda** [comment]
1、对的还是编辑器乱码。
2、同时还有一个地方出现乱码：
     点击最新》》选择一条帖子进入》》打开浏览器控制台发现报错“Uncaught SyntaxError: Invalid regular 
     expression: /['鈥橾/: Unterminated character class”报错文件是article-libs.min.js，不知道是不是由于同 
     一个原因导致的

**Comment by 88250** [comment]
执行 npm run build 重新打包一下前端代码试试。

**Comment by heilaoda** [comment]
我暂时找到方法了
1.发现tomcat8没乱码，tomcat9出现乱码
2.在intellij idea 的tomcat的vmoption配置加入-Dfile.encoding=UTF-8暂时解决了这个问题
