### ISSUE TITLE
github 账号绑定 有一些 不合适

### ISSUE THREAD

**Issue by gitors** [b3log/symphony#768]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/sym)搜寻资料解决问题。

----

### 描述问题

本人账号是早起已经绑定过github ，后期需要重新绑定时，一直显示未绑定（根据多次实际操作观察，应该是没有到偶数小时节点，没有刷新），后来 到了偶数小时节点刷新以后，才会显示数据，并显示未绑定状态。

### 重现步骤

请描述如何重现这个问题：
（前提：在sym 上 github 版本之前已经绑定了github 账号的）
1. 进入个人主页
2.点击 数据列表的github ，
3.显示未绑定，手动解绑重新绑定，依然显示未绑定
4.等待到了偶数小时系统刷新以后，个人主页github 节点才会显示github 数据，并明显区别出已绑定状态。

### 期待的结果

希望在绑定了github ，但是系统未更新数据到时候，显示“已绑定、待更新” 等相关提示，与“未绑定” 进行区别显示，避免误解。

### 截屏或录像

尝试过程中未保留截图。

### 桌面端环境

- OS: mac
- Browser : chrome
- Version :版本 68.0.3440.106（正式版本） （64 位）

### 移动端环境

无

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by Vanessa219** [comment]
Thx 😄
