### ISSUE TITLE
mvn构建错误

### ISSUE THREAD

**Issue by shminer** [b3log/symphony#796]
mvn 构建时缺少库  org.apache.maven.surefire.booter.ForkedBooter
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

pom.xml添加plugin

`<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.22.1</version>
    <configuration>
        <useSystemClassLoader>false</useSystemClassLoader>
    </configuration>
</plugin>`

**Comment by 88250** [comment]
用最新版的 maven 试试。

**Comment by shminer** [comment]
老大无时无刻不在啊  
加了plugin就好了
