### ISSUE TITLE
七牛图片上传域名问题

### ISSUE THREAD

**Issue by uliian** [b3log/symphony#834]
请描述如何重现这个问题：

1、建立一个七牛华南区的bucket，上传文件提示域名错误，需要变更为：https://up-z2.qiniup.com/

### 期待的结果

这一配置在js/settings.js中写死。这个域名能否进入配置？

**Comment by 88250** [comment]
这个问题之前有人提过 https://github.com/b3log/symphony/issues/617 ，但我觉得通过改代码更简单。
