### ISSUE TITLE
建议 API 返回的页码数据增加上一页，当前页，下一页页码数据

### ISSUE THREAD

**Issue by ronger-x** [b3log/symphony#837]
假设客户端调用 API 时传递页码为 100 而实际数据只有 99 页，客户端取自己传递的页码参数就会一直是错的，如果是后台返回了 99（纠正后的数据），客户端就可以取到正确的参数

**Comment by 88250** [comment]
![8ezrjnh7k1hotz qirue 0r](https://user-images.githubusercontent.com/873584/50537600-c934df80-0b9c-11e9-9af1-2d58a89ddc7f.png)

用这个可以判断。
