### ISSUE TITLE
期待可以有 docker 镜像

### ISSUE THREAD

**Issue by banduoba** [b3log/symphony#868]
### 你在什么场景下需要该功能？
一键搭建 不用配置开发环境,期待可以有 docker 镜像

**Comment by 88250** [comment]
开发环境配置下数据库， mvn jetty:run 就可以用了。Docker 暂时没有精力维护，见谅。

**Comment by banduoba** [comment]
https://hub.docker.com/r/88250/symphony/
这个可以用的么,我看构建都是失败的
<img width="1126" alt="wx20190212-145715 2x" src="https://user-images.githubusercontent.com/4811366/52617399-a2293780-2ed6-11e9-8242-f3a1de14716c.png">

**Comment by 88250** [comment]
这个就是 GitHub 这边自动推送的 https://github.com/b3log/symphony/blob/master/Dockerfile
