### ISSUE TITLE
库里无表的情况下启动，会报找不到表error 

### ISSUE THREAD

**Issue by punkmonday** [b3log/symphony#869]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/sym)搜寻资料解决问题。

----

### 描述问题

库里无表的情况下启动，会报找不到表error 

### 重现步骤

请描述如何重现这个问题：

1. 新建数据库，无表
2. 启动程序
3. 控制台提示找不到表错误信息

### 期待的结果

启动过程不要出现error

### 截屏或录像

https://github.com/b3log/symphony/blob/91f329af7e11f0f806c9cfa1f59e114b5ed48bd1/src/main/java/org/b3log/symphony/service/InitMgmtService.java#L221

### 其他信息

注：测试是在idea中启动，错误信息在控制台输出

**Comment by 88250** [comment]
这个问题只有在第一次启动初始化时会存在。后续启动不会报，暂时不处理了，感谢反馈。
