### ISSUE TITLE
我以为是全部开源呢

### ISSUE THREAD

**Issue by bambi2016** [b3log/symphony#917]
我下载了源代码，发现开源出来的不多好像

**Comment by Vanessa219** [comment]
我们用到的第三方库都在这里，也都是开源的。
![image](https://user-images.githubusercontent.com/970828/57494125-92b16300-72fa-11e9-9dc3-cd183388cd47.png)

**Comment by 88250** [comment]
是完全开源的，从业务实现到技术框架都是开源的。
