### ISSUE TITLE
发帖和修改帖子时，通知关注者的功能存在缺陷，修改不生效

### ISSUE THREAD

**Issue by qiankunpingtai** [b3log/symphony#920]
### 描述问题

发帖或者修改帖子，修改通知关注者选项，这个修改没有保存下来

### 其他信息
这个错误源于js中获取值的方式
articleNotifyFollowers: $('#articleNotifyFollowers').prop('checked')
这个方式获取到的是true或者false
但是数据库中存储的是int，所以在后台实际上保存的一直都是默认设置

**Comment by 88250** [comment]
这个值并不进行持久化，发布/更新帖子时根据当时的勾选状态进行通知或者不通知。

**Comment by 88250** [comment]
https://github.com/b3log/symphony/issues/903
