### ISSUE TITLE
执行原生sql提示字段找不到

### ISSUE THREAD

**Issue by qiankunpingtai** [b3log/symphony#921]
### 描述问题

原生sql在数据库可以执行通过，但是在sym项目中却提示了字段找不到的问题！
[INFO]-[2019-05-17 22:39:50]-[org.b3log.latke.repository.jdbc.util.JdbcUtil:150]: Executing SQL [select art.oId as article_oId from symphony_article art, symphony_tag_article ta where art.oId=ta.article_oId and art.articleDisplayable != ?]
[ERROR]-[2019-05-17 22:39:50]-[org.b3log.latke.repository.jdbc.JdbcRepository:512]: Select failed
java.sql.SQLException: Column 'oId' not found.

在数据库实际执行的sql为：
select art.oId as article_oId from symphony_article art, symphony_tag_article ta where art.oId=ta.article_oId 
and art.articleDisplayable != 0  and ta.tag_oId=1555340125273 order by ta.oId  desc  limit 0,60

**Comment by 88250** [comment]
Latke 暂时不支持 AS 别名，将在 https://github.com/b3log/latke/issues/149 中进行改进。

感谢反馈 ❤️
