### ISSUE TITLE
提一个不成熟的建议

### ISSUE THREAD

**Issue by dyb1296** [b3log/symphony#924]
发帖子的时候选择标签，为啥不做选择而作输入呢..各位大佬..

**Comment by 88250** [comment]
配置领域后就可以选择了。

**Comment by dyb1296** [comment]
管理帖子的时候呢

**Comment by 88250** [comment]
管理的时候手动输入一下吧，浏览器一般都有历史记录，会自动补全的。

**Comment by dyb1296** [comment]
当一个领域A下面如果有标签AB，另一个领域B下面也有标签AB，那么在A领域AB标签下发的帖子在B领域也能看见，有时候也许AB相关，但是绝大多数情况，A领域的AB标签和B领域的AB标签代表的事物不一样呢

**Comment by dyb1296** [comment]
比如领域A是中学，领域B是小学，中学小学都有数学这个标签，但是本来发来中学领域的帖子也可以被小学互相看见，我觉得这个逻辑有点小小的问题呢

**Comment by 88250** [comment]
标签是平铺的，你可以用中学数学、小学数学区分，如果需要的话同时再加一个数学标签。
