### ISSUE TITLE
添加mybatis支持

### ISSUE THREAD

**Issue by qiankunpingtai** [b3log/symphony#926]
### 你在什么场景下需要该功能？

多表关联查询时，latke只能通过原生sql去实现，拼装sql的过程异常费力，拼装sql的代码可读性也非常差。

### 描述可能的解决方案

建议集成mybatis或者MyBatis-Plus来提高多表操作的开发效率

**Comment by 88250** [comment]
可以通过 Lakte 获取 JDBC 连接，然后引入其他库操作数据库。
