### ISSUE TITLE
可设置帖子在列表中是否展示

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#927]
https://github.com/b3log/symphony/pull/925

**Comment by 88250** [comment]
@qiankunpingtai 做了一些调整：

1. 删除是否进搜索库的开关。我觉得这个配置项不容易理解，并且大多数场景下内容都是要进搜索库的，不然搜索不到了
2. 重命名 articleDisplayable 为 articleShowInList。这样更容易理解，不会造成误解
3. 调整编码风格，删掉多余的注释

另外关于领域、标签列表查询实现使用的原生 SQL 那块我没有仔细测试，从代码上看可能会有点问题：表名没有使用 repository.getName 获取，这样如果用户配置了表前缀的话应该会报错的。

暂时就这些调整，再次感谢你的 PR :heart:

**Comment by qiankunpingtai** [comment]
关于表名没有使用 repository.getName 获取这一点，我感觉你可能理解错了
实现代码如下
`StringBuffer queryStr=new StringBuffer(articleRepository.getName()+" symphony_article, ").append(tagArticleRepository.getName()+" symphony_tag_article ");`
这里出现的symphony_article以及symphony_tag_article是表的别名，真实的表名是通过articleRepository.getName()和tagArticleRepository.getName()获取的

**Comment by 88250** [comment]
好的，谢谢。
