### ISSUE TITLE
docker启动参数错误

### ISSUE THREAD

**Issue by starwonder** [b3log/symphony#932]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题
首页：https://github.com/b3log/symphony
中关于docker启动参数的示例有一处错误：
docker run --detach --name sym --network=host \
    --env RUNTIME_DB="MYSQL" \
    --env JDBC_USERNAME="root" \
    --env JDBC_PASSWORD="123456" \
    --env JDBC_DRIVER="com.mysql.cj.jdbc.Driver" \
    --env JDBC_URL="jdbc:mysql://127.0.0.1:3306/symphony?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC" \
    b3log/symphony --listen_port=8080 --server_scheme=http --server_host=localhost 

这里的：
--listen_port=8080
应该是：
--server_port=8080

### 截屏或录像
![image](https://user-images.githubusercontent.com/15991668/58784274-94c6c300-8615-11e9-9edc-a828bfafe236.png)

**Comment by 88250** [comment]
你好，这是两个不同的参数，都可以配置的。
