### ISSUE TITLE
memcache

### ISSUE THREAD

**Issue by LiTeng51** [b3log/symphony#950]
请问有支持memcache吗？or  redis？

**Comment by 88250** [comment]
latke.props 中可配置 `runtimeCache=REDIS`。

**Comment by LiTeng51** [comment]
> latke.props 中可配置 `runtimeCache=REDIS`。
> 
> ```
> runtimeCache=REDIS
> 
> redis.host=localhost
> redis.port=6379
> redis.password=
> redis.minConnCnt=5
> redis.maxConnCnt=10
> redis.waitTime=100
> ```

**Comment by LiTeng51** [comment]
> latke.props 中可配置 `runtimeCache=REDIS`。
> 
> ```
> runtimeCache=REDIS
> 
> redis.host=localhost
> redis.port=6379
> redis.password=
> redis.minConnCnt=5
> redis.maxConnCnt=10
> redis.waitTime=100
> ```

意思就是只支持redis？

**Comment by 88250** [comment]
是的，目前仅支持内存缓存和 Redis 两种。
