### ISSUE TITLE
Is there an english version?

### ISSUE THREAD

**Issue by godadada** [b3log/symphony#955]
### 你在什么场景下需要该功能？
80% Internet uses English.
请尽量清晰精准地描述你碰到的问题。

### 描述可能的解决方案
enough said
请尽量清晰精准地描述你期待我们要做的，描述你想到的实现方案。
obvious
### 描述你认为的候选方案

请尽量清晰精准地描述你能接受的候选解决方案。

### 其他信息

请提供关于该功能建议的其他附加信息。

**Comment by godadada** [comment]
found. Thanks.

**Comment by 88250** [comment]
你好！

1. 程序本身支持多语言，内置了英语版的配置
2. 项目相关文档是中文的，暂时没有时间精力做国际化，如果有空欢迎帮助我们完善，谢谢
