### ISSUE TITLE
echarts 图表功能对和弦图 和力导向布局图 等特性不支持

### ISSUE THREAD

**Issue by qiankunpingtai** [b3log/symphony#957]
### 描述问题

echarts 图表功能对和弦图 和力导向布局图 等特性不支持;
和弦图示例：
[markdown 由简入繁，上手跟我做（十六）echarts 图表 - 和弦图](https://qiankunpingtai.cn/article/1566376428150) 
力导向布局图示例：
[markdown 由简入繁，上手跟我做（十七）echarts 图表 - 力导向布局图](https://qiankunpingtai.cn/article/1566376789648) 
### 错误提示
![图片](https://user-images.githubusercontent.com/46507972/63417533-0ef82e00-c434-11e9-9821-6ebf24ee90a4.png)

![图片](https://user-images.githubusercontent.com/46507972/63417509-fee04e80-c433-11e9-81b1-3d467894ad12.png)

**Comment by Vanessa219** [comment]
这个是 echarts 使用错误，具体使用方法可参考 https://www.echartsjs.com

**Comment by qiankunpingtai** [comment]
```echarts
`echarts代码`
```
echarts代码这里目前只支持json吗？

另外这个echarts怎么支持动态的图表呢？

**Comment by Vanessa219** [comment]
可参见 https://hacpai.com/guide/markdown
