### ISSUE TITLE
:gift_heart: 显示成乱码 ，如下图

### ISSUE THREAD

**Issue by justime** [b3log/symphony#958]
系统初始化数据： 欢迎来到 Sym 社区 :gift_heart:  在文章详情页面显示乱码。   顺便问下  :gift_heart: 是用来获取啥数据的？

**Comment by justime** [comment]
![1](https://user-images.githubusercontent.com/17840003/63848078-bbe92280-c9c1-11e9-8c83-0671f1718546.png)
![2](https://user-images.githubusercontent.com/17840003/63848092-bee41300-c9c1-11e9-8293-c50825d99cda.png)

**Comment by 88250** [comment]
看上去是数据库编码的问题，请用 utf8mb4。

**Comment by justime** [comment]
数据库编码是用 utf8mb4 的

**Comment by justime** [comment]
> 看上去是数据库编码的问题，请用 utf8mb4。

数据库编码是用 utf8mb4 的

**Comment by 88250** [comment]
麻烦提供一下环境信息，比如操作系统、数据库、浏览器等。

**Comment by justime** [comment]
> 麻烦提供一下环境信息，比如操作系统、数据库、浏览器等。
我的锅，jetty 启动选了默认的版本6.X，改成9.X 问题解决

**Comment by justime** [comment]
另外问个问题，思维导图中的功能都做好了吗？

**Comment by 88250** [comment]
> 另外问个问题，思维导图中的功能都做好了吗？

做好了，不过有的功能是商业版里的。
