### ISSUE TITLE
Markdown HTTP 渲染引擎切换为 Lute

### ISSUE THREAD

**Issue by 88250** [b3log/symphony#959]
之前使用的是 [markdown-http](https://github.com/b3log/markdown-http)，切换为 [Lute](https://github.com/b3log/lute)。

**Comment by Vanessa219** [comment]
* 后面的标题无法渲染
```
### 数学公式

$$a^2 + b^2 = \color{red}c^2$$

### 流程图
```
* 启用 lute 后代码块上无 `highlight-chroma` class
