### ISSUE TITLE
Sym部署SSL问题

### ISSUE THREAD

**Issue by thrfur** [b3log/symphony#962]
- CentOS 7系统通过宝塔面板环境，成功将Sym搭建成功 .（域名.com访问）

- 现在有SSL证书要开启，在宝塔面板里强制了**SSL**，访问时又出现了 {  **Latke 配置剖析**  }问题 .

- 按下 **F12**显示，各链接请求地址仍为 **HTTP** .

- 遂修改文件 【 **latke.properties** 】.

- 修改 serverScheme=**http**  **→**  serverScheme=**https** .

- 设置反代后，问题依然未解决 .

**Comment by 88250** [comment]
* serverScheme 修改后需要重启
* F12 看下是否协议都是 HTTPS

**Comment by thrfur** [comment]
- 新问题。

- [ ] 设置反代后，域名可以访问。但是点击网站内的任一链接，新开链接都是IP地址链接，修改了【 latke.properties 】里的 【 serverHost= 】为我的域名，也重启了。错误还是如此。

**Comment by 88250** [comment]
理论上改了重启就会生效，你找下其他原因吧。
