### ISSUE TITLE
修改帖子时有xss漏洞,版本(3.5.1)

### ISSUE THREAD

**Issue by thiscodecc** [b3log/symphony#970]
根据此项目报告安全漏洞的策略.
<img width="1079" alt="20000" src="https://user-images.githubusercontent.com/55778895/66256003-4b9da000-e7bc-11e9-8c42-c9480539cee5.png">

我已将具体漏洞详情发邮件至你的邮箱 **os@b3log.org** 注意查收.

**Comment by 88250** [comment]
感谢反馈，已经收到邮件。稍后修复后会将你的报告附件进行披露。

**Comment by 88250** [comment]
漏洞细节报告披露：[symphony(3.5.1)修改帖子时存在xss漏洞.docx](https://github.com/b3log/symphony/files/3693397/symphony.3.5.1.xss.docx)

提交 fef63c275 中进行修复。
