### ISSUE TITLE
数学公式在预览的时候解析不出来了

### ISSUE THREAD

**Issue by qiankunpingtai** [b3log/symphony#972]
### 描述问题
数学公式在预览是不能正常解析，帖子发出后解析正常
预览时：
![图片](https://user-images.githubusercontent.com/46507972/66618017-17860d00-ec0a-11e9-8262-6819b870bd80.png)
发帖后：
![图片](https://user-images.githubusercontent.com/46507972/66618056-47cdab80-ec0a-11e9-8cc3-f3dc42191859.png)

**Comment by 88250** [comment]
请用 Lute HTTP https://hacpai.com/article/1569240189601
