### ISSUE TITLE
头像更新问题

### ISSUE THREAD

**Issue by jetablezhu** [b3log/symphony#976]
论坛使用的头像不应该是从GitHub获取的avatar链接么？为什么我在avatar中改了头像，论坛里始终没有更新，但是GitHub已经更新了。你是把头像缓存在论坛系统里了？以后改头像只能去论坛中修改么？

**Comment by 88250** [comment]
是的，只有第一次注册时是拉取 GitHub 的，后续需要在社区中自行修改。
